// RemotePi worker entry — M2 routing + Worker Static Assets SPA.
//
// Endpoints (each routed to this script via `run_worker_first` in
// wrangler.toml; any other path falls through to the asset worker):
//   GET /healthz     — plain text ops smoke probe (was `GET /` until
//                      2026-09-05, moved because the root now serves
//                      the web SPA). Continues to use PROTOCOL_VERSION
//                      from shared so the probe fails loudly if someone
//                      bumps the protocol without deploying the new
//                      bundle.
//   UPGRADE /web     — WebSocket upgrade for browser sessions.
//   UPGRADE /bridge  — WebSocket upgrade for the local bridge daemon.
//
// Auth is bound to the WebSocket subprotocol: the client must present
// `Sec-WebSocket-Protocol: remotepi.v1, <token>` (see envelope.md §锁版承诺).
// Token is **only** extracted from this header — we deliberately do not fall
// back to URL query parameters, because the v1 lock-version promises that
// token propagation goes through subprotocol. If CF ever strips the header in
// production we will see it via the 401 path here and treat it as a protocol
// deviation worth recording (per PRD §3 + envelope.md).
//
// The chosen role (web/bridge) is propagated to the Room DO via the
// `X-RemotePi-Role` request header on the forwarded Request. The DO reads it
// in `fetch` and uses it for the handshake role check. Using a header (rather
// than a URL parameter on the forwarded request) keeps the original URL
// intact — the DO's `request.url` still reflects `/web` or `/bridge` for any
// future logging or routing decisions.

// `GET /` is intentionally NOT handled here. wrangler.toml routes it to the
// Static Assets worker, which serves `packages/web/dist/index.html` (or the
// SPA fallback for any unmatched path under `not_found_handling =
// "single-page-application"`). Putting a hello-text handler on `/` would
// shadow the web app, so we moved the smoke probe to `/healthz` and added
// it to `run_worker_first` so it's reachable through the Worker script.
import { PROTOCOL_VERSION, type Role } from '@remotepi/shared';
import type { Env } from './env.js';

export type { Env } from './env.js';
export { Room } from './room.js';

const HEALTHZ_TEXT = `ok from remotepi worker v${PROTOCOL_VERSION}`;
const PLAIN = { 'content-type': 'text/plain; charset=utf-8' } as const;
const SUBPROTOCOL_VERSION = 'remotepi.v1';
// X-RemotePi-Role: inner-only — never appears on the 101 response.
// The header travels on the forwarded Request to the per-token Room DO
// (which reads it via `request.headers.get(ROLE_HEADER)` in `fetch()`).
// It is NOT echoed back on the upgrade response — that response is the
// 101 Switching Protocols and is generated by the runtime, not us.
const ROLE_HEADER = 'x-remotepi-role'; // lowercased per HTTP/2 conventions

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    // Plain health probe — replaces the M1 `GET /` hello. `/healthz` is
    // listed in wrangler.toml's `run_worker_first` so it reaches this
    // script ahead of the asset worker (an SPA fallback would otherwise
    // serve the web app's index.html here, which is not a valid probe).
    if (url.pathname === '/healthz' && request.method === 'GET') {
      return new Response(HEALTHZ_TEXT, { status: 200, headers: PLAIN });
    }

    if (url.pathname === '/web' || url.pathname === '/bridge') {
      const expectedRole: Role = url.pathname === '/web' ? 'web' : 'bridge';

      // Reject non-upgrade traffic with 426 — RFC 7231 §6.5.15.
      const upgradeHeader = request.headers.get('upgrade');
      if (upgradeHeader === null || upgradeHeader.toLowerCase() !== 'websocket') {
        return new Response('Upgrade Required', { status: 426, headers: PLAIN });
      }

      const token = extractToken(request.headers.get('sec-websocket-protocol'));
      if (token === null) {
        return new Response('Unauthorized', { status: 401, headers: PLAIN });
      }

      // Forward to the per-token Room with the expected role annotated on the
      // request. Cloning the headers avoids mutating the incoming request —
      // Request objects can be observed by the runtime after we return.
      const stubHeaders = new Headers(request.headers);
      stubHeaders.set(ROLE_HEADER, expectedRole);
      const stubReq = new Request(request.url, {
        method: request.method,
        headers: stubHeaders,
      });

      const id = env.ROOM.idFromName(token);
      const stub = env.ROOM.get(id);
      return stub.fetch(stubReq);
    }

    return new Response('Not Found', { status: 404, headers: PLAIN });
  },
} satisfies ExportedHandler<Env>;

/** Pull `<token>` from a `Sec-WebSocket-Protocol: remotepi.v1, <token>` header.
 *  Returns `null` for missing, malformed, version-mismatched, or empty tokens.
 *
 *  Splits on `,` and trims whitespace — clients may serialize the list as
 *  `"remotepi.v1,<token>"` (no space) or `"remotepi.v1, <token>"`. We treat
 *  both as equivalent. We require exactly two items per the v1 lock-version. */
function extractToken(header: string | null): string | null {
  if (header === null) return null;
  const parts = header.split(',').map((p) => p.trim());
  if (parts.length !== 2) return null;
  const versionTag = parts[0];
  const token = parts[1];
  if (versionTag === undefined || token === undefined) return null;
  if (versionTag !== SUBPROTOCOL_VERSION) return null;
  if (token.length === 0) return null;
  return token;
}