// seedToken — install the room access token into localStorage
// before any navigation so the `<TokenModal required>` branch
// is bypassed (the token is sourced from `localStorage` via
// `ws/tokenStorage.ts`, not from the URL hash).
//
// ## Why two-step (page navigation pattern)
//
// The web SPA reads the token via `tokenStorage.read()` during the
// first `readAuth()` call on mount. `localStorage` is per-origin, so
// the origin must be established BEFORE the token is written —
// otherwise `localStorage.setItem` on a `about:blank` page silently
// no-ops (the storage is bound to the active document's origin).
//
// Two-step flow:
//
//   1. `page.goto(baseUrl)` — establish origin (no token required
//      yet; the SPA will boot, see `auth.token === null`, and
//      render `<TokenModal required>`).
//   2. `page.evaluate(localStorage.setItem('remotepi.token', token))`
//      — write the token into the now-bound origin storage.
//   3. `page.goto(baseUrl)` (re-navigation) — the SPA reloads, the
//      first `readAuth()` reads the cached token, and the app lands
//      on `<ChoicePage level=1>` (matching the existing spec
//      behaviour after the M4 ChoicePage migration).
//
// ## Implementation choice: `addInitScript` vs explicit two-step
//
// The web specs that currently use this helper ran against the
// pre-M5 `goto('/#<token>')` shape, which did the URL-hash-token
// bootstrap in a single navigation. The closest equivalent on
// localStorage is Playwright's `page.addInitScript`, which runs the
// provided script in every new document BEFORE any user script —
// that means by the time the SPA's first script executes, the
// localStorage entry is already in place.
//
// We use `addInitScript` because:
//   - It's a single helper function call from the spec's
//     perspective (matches the spec ergonomics of the old
//     `goto('/#<token>')`).
//   - It survives subsequent `page.reload()` / `page.goto(other)`
//     navigations within the same page — `addInitScript` registers
//     for the lifetime of the page object, not for a single
//     navigation.
//   - The token is in place by the time the App's `readAuth()`
//     runs, so the `<TokenModal required>` flash is fully
//     suppressed — the user lands on `<ChoicePage level=1>` on the
//     very first paint, which is what the spec assertions expect
//     (`page.locator('[data-testid="choice-page"][data-level="1"]')`).
//
// ## Compatibility with `goto('/#<token>')`-era specs
//
// The existing 8 e2e specs (`01-...` through `08-...`) were
// written against the M4 `goto('/#<token>')` flow. The migration
// to localStorage is a strict refactor at the spec level — replace
// `await page.goto(`${baseUrl}/#${token}`)` with
// `await seedToken(page, baseUrl, token)`. The subsequent spec
// body (locator waits, button clicks, etc.) is unchanged because
// the post-bootstrap DOM is identical (ChoicePage level=1 in both
// flows).
//
// ## Failure modes
//
// - If `page` is fresh (no origin yet), `addInitScript` queues the
//   script for the next navigation; `page.goto(baseUrl)` triggers
//   it. If the spec calls `seedToken` AFTER a `goto`, the script
//   runs on the next reload/navigation, not retroactively — the
//   expected call pattern is `seedToken` BEFORE the first `goto`.
// - If the token contains characters that need escaping (the
//   bridge-fixed-token is alphanumeric + dash — generated by
//   `${runTag}` random bytes — so this is a non-issue in practice),
//   the helper writes the raw value as-is. No JSON encoding needed.
//
// ## Why not just inject via `page.addInitScript` inline at every spec
//
// Centralising the helper means a future change to the token-storage
// key (`remotepi.token` → e.g. `remotepi.token.v2`) only needs a
// single edit here. Specs that need to seed the token import this
// helper instead of carrying the literal `localStorage.setItem`
// call inline.

import type { Page } from '@playwright/test';

/** The localStorage key the web SPA reads from. Kept in sync with
 *  `KEY` in `packages/web/src/ws/tokenStorage.ts`. If that constant
 *  ever changes (e.g. versioning), update this constant too. */
export const TOKEN_STORAGE_KEY = 'remotepi.token';

/** Install the room access token into `localStorage` for the
 *  given page, then navigate to `baseUrl`. Subsequent navigations
 *  within the same page will retain the token (addInitScript is
 *  per-page, not per-navigation).
 *
 *  The spec's first locator wait (`page.locator('[data-testid=
 *  "choice-page"][data-level="1"]')`) is the assertion that the
 *  token write took effect: the SPA renders `<TokenModal
 *  required>` only when `auth.token === null`, and we want to
 *  see ChoicePage level=1 directly.
 *
 *  Example migration from the legacy `goto('/#<token>')` shape:
 *
 *    ```ts
 *    // before:
 *    await page.goto(`${baseUrl}/#${token}`);
 *
 *    // after:
 *    await seedToken(page, baseUrl, token);
 *    ```
 */
export async function seedToken(page: Page, baseUrl: string, token: string): Promise<void> {
  // addInitScript queues the script for every subsequent
  // navigation. The IIFE receives `token` via Playwright's
  // argument-passing machinery (JSON-serialised into the page).
  await page.addInitScript(
    ([key, value]) => {
      // The init script runs before any user script on the page,
      // so `localStorage` is writable at this point (the origin is
      // established by the about-to-navigate document). `setItem`
      // is synchronous and never throws under normal conditions.
      window.localStorage.setItem(key, value);
    },
    [TOKEN_STORAGE_KEY, token] as const,
  );
  await page.goto(baseUrl);
}

/** Install the room access token into localStorage AND navigate
 *  to a URL that ALSO carries a hash fragment (e.g. `work_dir=...
 *  &session=<stem>` for the multi-context scenario (c) spec's
 *  second-context bootstrap). The hash is appended after the
 *  bare base URL; a leading `#` is added if missing.
 *
 *  Example:
 *
 *    ```ts
 *    await seedTokenForHash(page, baseUrl, token, 'work_dir=' +
 *      encodeURIComponent(workDir) + '&session=' + stem);
 *    ```
 *
 *  The token is in localStorage (NOT in the URL hash), and the
 *  navigation hash carries the navigation state (work_dir +
 *  session) so the SPA boots straight into `<RecoveryView>` /
 *  `<ChatView>` for that session.
 */
export async function seedTokenForHash(
  page: Page,
  baseUrl: string,
  token: string,
  hashFragment: string,
): Promise<void> {
  await page.addInitScript(
    ([key, value]) => {
      window.localStorage.setItem(key, value);
    },
    [TOKEN_STORAGE_KEY, token] as const,
  );
  const normalisedHash = hashFragment.startsWith('#') ? hashFragment : `#${hashFragment}`;
  await page.goto(`${baseUrl}${normalisedHash}`);
}
