// RemotePi web — single WebSocket client (control plane only).
//
// Wires up one persistent connection to the worker domain at
// `${VITE_WSS_URL}/web`, carrying the access token in the URL fragment + the
// second element of the WebSocket subprotocol (per architecture/protocol/
// envelope.md §锁版承诺 and control.md §1).
//
// Responsibilities:
//   - On open: send the control/handshake frame with `{role:'web', token}`.
//   - Send a control/ping every 20s (heartbeat) — generated by us, the
//     counterparty may also ping us; we reply with control/pong carrying
//     the same nonce (control.md §2 / §3).
//   - On pong: clear the matching timer, compute RTT, reset failure counter.
//     Three consecutive timeouts in a row → close + reconnect.
//   - On bridge_status: surface `online` / `changed_at` / `reason` to the UI.
//   - On invalid envelope: console.warn and discard (web is read-only on
//     the error channel — we never emit `error` frames outbound).
//   - On close / error: state machine drops to `offline`, and unless the
//     caller explicitly disconnected, schedule an exponential reconnect
//     (base 1s, cap 30s, ±20% jitter).
//
// React glue lives in `WsClientContext.tsx`; this file is framework-free so
// the protocol logic stays unit-testable in isolation if/when we add tests.

import {
  Envelope,
  PROTOCOL_VERSION,
  type Envelope as EnvelopeType,
  type PingPayload,
  type PongPayload,
} from '@remotepi/shared';

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/** Tri-state connection machine surfaced by the StatusBar component. */
export type ConnState = 'connecting' | 'online' | 'offline';

/** Latest bridge_status snapshot broadcast by the worker (control.md §4). */
export interface BridgeStatusInfo {
  online: boolean;
  /** ISO-8601 timestamp from the worker (BridgeStatusPayload.changed_at). */
  changedAt: string;
  reason: 'connected' | 'closed' | 'stale';
  /** Local clock at the moment we observed the frame — for UI ordering. */
  receivedAt: number;
}

/** One row in BroadcastLog — every successfully parsed inbound envelope. */
export interface LogEntry {
  receivedAt: number;
  envelope: EnvelopeType;
}

/** One ping's outcome — surfaced by PingTester. `rttMs === null` ⇒ timed out. */
export interface PingHistoryEntry {
  nonce: string;
  sentAt: number;
  /** Round-trip in milliseconds; `null` if no matching pong arrived in time. */
  rttMs: number | null;
}

/** Handler signature for type-scoped subscriptions (`ws.on('pong', …)`). */
export type EnvelopeHandler = (envelope: EnvelopeType) => void;

// ---------------------------------------------------------------------------
// Constants — pulled out for readability and to make the protocol contract
// easy to audit against docs/architecture/protocol/control.md.
// ---------------------------------------------------------------------------

/** Subprotocol slot 0 — version tag, see envelope.md §锁版承诺. */
const SUBPROTOCOL_VERSION = 'remotepi.v1';

/** Heartbeat cadence — control.md §2 (also §配套常量). */
const PING_INTERVAL_MS = 20_000;

/** Per-ping deadline before counting it as a miss — control.md §3. */
const PONG_TIMEOUT_MS = 30_000;

/** Consecutive misses tolerated before we declare the peer dead. */
const PONG_FAIL_LIMIT = 3;

/** Exponential reconnect base, capped at RECONNECT_CAP_MS. */
const RECONNECT_BASE_MS = 1_000;
const RECONNECT_CAP_MS = 30_000;
/** ±20% jitter matches the bridge client (PRD §2 / §6). */
const RECONNECT_JITTER_RATIO = 0.2;

/** Inbound log buffer cap — per the spec. */
const LOG_CAP = 200;
/** PingTester history cap — small ring buffer, newest first. */
const PING_HISTORY_CAP = 20;

// ---------------------------------------------------------------------------
// WsClient — plain class, no React dependency
// ---------------------------------------------------------------------------

export class WsClient {
  private readonly url: string;

  private socket: WebSocket | null = null;
  private token: string | null = null;

  // Connection machine state -------------------------------------------------
  private _connState: ConnState = 'offline';
  private _bridgeStatus: BridgeStatusInfo | null = null;
  private _logs: LogEntry[] = [];
  private _pingHistory: PingHistoryEntry[] = [];

  // Heartbeat bookkeeping ----------------------------------------------------
  private pingTimer: ReturnType<typeof setInterval> | null = null;
  /** Outstanding outbound nonces and the timeout awaiting their pong. */
  private pendingPings = new Map<
    string,
    { sentAt: number; timer: ReturnType<typeof setTimeout> }
  >();
  private consecutiveFailures = 0;

  // Reconnect bookkeeping ----------------------------------------------------
  private reconnectAttempt = 0;
  private reconnectTimer: ReturnType<typeof setTimeout> | null = null;
  /** Set false by `disconnect()` to suppress the auto-reconnect loop. */
  private shouldReconnect = false;

  // Subscriptions ------------------------------------------------------------
  /** State listeners (used by useSyncExternalStore). */
  private stateListeners = new Set<() => void>();
  /** Type-scoped envelope listeners (`ws.on('pong', handler)`). */
  private typeListeners = new Map<EnvelopeType['type'], Set<EnvelopeHandler>>();

  constructor(url: string) {
    this.url = url;
  }

  // ---- Read-only state ------------------------------------------------------

  get connState(): ConnState {
    return this._connState;
  }

  get bridgeStatus(): BridgeStatusInfo | null {
    return this._bridgeStatus;
  }

  get logs(): readonly LogEntry[] {
    return this._logs;
  }

  get pingHistory(): readonly PingHistoryEntry[] {
    return this._pingHistory;
  }

  // ---- Subscriptions -------------------------------------------------------

  /**
   * Subscribe to ANY state change. Used by `useSyncExternalStore` —
   * `getSnapshot` is called on every fire; the React layer decides whether
   * the returned slice changed identity and skips re-render if not.
   */
  subscribe = (listener: () => void): (() => void) => {
    this.stateListeners.add(listener);
    return () => {
      this.stateListeners.delete(listener);
    };
  };

  /**
   * Subscribe to a specific envelope type. The handler is called once per
   * inbound frame whose `type` matches. Returns an unsubscribe function.
   *
   * Inbound envelopes are also always appended to `logs` regardless of
   * whether anyone is subscribed — `BroadcastLog` reads the log buffer
   * rather than registering a per-type handler.
   */
  on(type: EnvelopeType['type'], handler: EnvelopeHandler): () => void {
    let set = this.typeListeners.get(type);
    if (!set) {
      set = new Set();
      this.typeListeners.set(type, set);
    }
    set.add(handler);
    return () => {
      set?.delete(handler);
    };
  }

  // ---- Lifecycle -----------------------------------------------------------

  /**
   * Open a new connection (closing any existing one). `token` must be the
   * non-empty value parsed from `location.hash` — it travels in slot 1 of
   * the WebSocket subprotocol AND in the handshake payload, per envelope.md
   * §锁版承诺.
   */
  connect(token: string): void {
    if (!token) return;
    this.teardownSocket();
    this.token = token;
    this.shouldReconnect = true;
    this.openSocket();
  }

  /** Close and stay closed. Cancels any pending reconnect timer. */
  disconnect(): void {
    this.shouldReconnect = false;
    this.clearReconnectTimer();
    this.teardownSocket();
    if (this._connState !== 'offline') {
      this.setConnState('offline');
    }
  }

  // ---- Outbound ------------------------------------------------------------

  /**
   * Send a fully-formed envelope. Caller is responsible for `v` / `kind` /
   * `id` / `payload` shape — this method does not auto-fill. The protocol
   * expects every outbound frame to carry a unique `id`; use `crypto.randomUUID`.
   */
  send(envelope: EnvelopeType): void {
    this.sendRaw(envelope);
  }

  /**
   * Convenience for the PingTester button: build and send a control/ping,
   * arm the 30s pong deadline, and record the entry in `pingHistory` so
   * the component can render the RTT (or "timed out") when pong arrives.
   *
   * Returns the generated nonce so the UI can render it before the round
   * trip completes.
   */
  sendManualPing(): string {
    const nonce = this.makeNonce();
    this.armPing(nonce);
    return nonce;
  }

  // ---- Internals: socket lifecycle ----------------------------------------

  private openSocket(): void {
    if (!this.token) return;
    this.setConnState('connecting');

    let socket: WebSocket;
    try {
      // Slot 0 = version, slot 1 = token (envelope.md §锁版承诺). The token
      // travels separately from the URL so it isn't logged in proxy/CDN
      // access logs.
      socket = new WebSocket(this.url, [SUBPROTOCOL_VERSION, this.token]);
    } catch (err) {
      console.warn('[WsClient] WebSocket construction failed:', err);
      this.scheduleReconnect();
      return;
    }
    this.socket = socket;

    socket.addEventListener('open', this.handleOpen);
    socket.addEventListener('message', this.handleMessage);
    socket.addEventListener('close', this.handleClose);
    socket.addEventListener('error', this.handleError);
  }

  private teardownSocket(): void {
    this.clearHeartbeat();
    if (this.socket) {
      // removeEventListener is a no-op for listeners that weren't registered,
      // so the cleanup path stays straightforward.
      this.socket.close();
      this.socket = null;
    }
  }

  private handleOpen = (): void => {
    this.reconnectAttempt = 0;
    this.consecutiveFailures = 0;
    if (this.token) {
      const handshake = {
        v: PROTOCOL_VERSION,
        kind: 'control' as const,
        type: 'handshake' as const,
        id: this.makeId(),
        payload: { role: 'web' as const, token: this.token },
      };
      this.sendRaw(handshake);
    }
    this.setConnState('online');
    this.startHeartbeat();
  };

  private handleMessage = (event: MessageEvent): void => {
    // Drop messages from a stale socket — happens when connect() swapped
    // us onto a new token mid-flight: the old socket's close has been
    // requested but its buffered message event may still fire on us.
    if (!this.isCurrentSocket(event.target)) return;
    let raw: unknown;
    try {
      raw = JSON.parse(typeof event.data === 'string' ? event.data : '');
    } catch (err) {
      console.warn('[WsClient] inbound JSON parse failed:', err);
      return;
    }
    const parsed = Envelope.safeParse(raw);
    if (!parsed.success) {
      // Per spec: web only logs invalid frames — we never originate `error`
      // frames, so the worker can't tell us "you sent garbage". Drop quietly.
      console.warn('[WsClient] inbound envelope failed schema, discarding:', parsed.error.message);
      return;
    }
    const envelope = parsed.data;
    this.appendLog(envelope);
    this.dispatchTypeListeners(envelope);
    this.handleControlFrame(envelope);
  };

  private dispatchTypeListeners(envelope: EnvelopeType): void {
    const set = this.typeListeners.get(envelope.type);
    if (!set) return;
    for (const handler of set) {
      try {
        handler(envelope);
      } catch (err) {
        // A buggy handler must not break the message loop for other subs.
        console.warn('[WsClient] type listener threw:', err);
      }
    }
  }

  private handleControlFrame(envelope: EnvelopeType): void {
    switch (envelope.type) {
      case 'ping': {
        // Server-initiated liveness probe — reply with pong carrying the
        // same nonce (or empty if the probe arrived without one). The worker's
        // own heartbeat (§3 of control.md + DO 主动探活) routes through here.
        const pong = {
          v: PROTOCOL_VERSION,
          kind: 'control' as const,
          type: 'pong' as const,
          id: this.makeId(),
          payload: { nonce: envelope.payload.nonce ?? '' },
        };
        this.sendRaw(pong);
        break;
      }
      case 'pong': {
        this.handlePong(envelope.payload);
        break;
      }
      case 'bridge_status': {
        this.setBridgeStatus({
          online: envelope.payload.online,
          changedAt: envelope.payload.changed_at,
          reason: envelope.payload.reason,
          receivedAt: Date.now(),
        });
        break;
      }
      case 'handshake':
      case 'error':
        // Server-to-client frames we don't act on: the worker never sends
        // us handshakes (we are the initiator), and web is read-only on the
        // error channel. Both still show up in BroadcastLog via appendLog().
        break;
    }
  }

  private handleClose = (event: CloseEvent): void => {
    // Same stale-event guard as handleMessage — when teardownSocket() closed
    // a prior socket (e.g. during token swap), the close event still fires
    // on it AFTER we've moved on. Comparing event.target to `this.socket`
    // detects that case and lets us skip the (now incorrect) reconnect.
    if (!this.isCurrentSocket(event.target)) return;
    this.socket = null;
    this.clearHeartbeat();
    if (this._connState !== 'offline') {
      this.setConnState('offline');
    }
    if (this.shouldReconnect) {
      this.scheduleReconnect();
    }
  };

  private handleError = (event: Event): void => {
    // Mirror the close guard: stale errors from a previous socket must not
    // flip the *current* connection into the offline state. The real close
    // event will follow for the active socket and drives the reconnect.
    //
    // We unconditionally set offline here — the redundant `connState ===
    // 'online'` guard from before this fix was misleading. The browser/Node
    // contract is that every `error` event is followed by a `close` event
    // on the same socket (per the WHATWG HTML spec); handleClose is the
    // authoritative path that clears the socket and schedules the
    // reconnect. handleError exists only to flip the visible status
    // earlier so the UI doesn't sit on a stale 'online' label while the
    // closing handshake is still draining.
    if (!this.isCurrentSocket(event.target)) return;
    this.setConnState('offline');
  };

  /**
   * True iff `target` is the WebSocket we currently consider live. Used to
   * discard late events from a socket that was replaced via connect().
   */
  private isCurrentSocket(target: EventTarget | null): boolean {
    return target !== null && target === this.socket;
  }

  // ---- Internals: heartbeat ------------------------------------------------

  private startHeartbeat(): void {
    this.clearHeartbeat();
    this.pingTimer = setInterval(() => {
      this.armPing(this.makeNonce());
    }, PING_INTERVAL_MS);
  }

  private clearHeartbeat(): void {
    if (this.pingTimer) {
      clearInterval(this.pingTimer);
      this.pingTimer = null;
    }
    for (const pending of this.pendingPings.values()) {
      clearTimeout(pending.timer);
    }
    this.pendingPings.clear();
    this.consecutiveFailures = 0;
  }

  /**
   * Send a ping with the given nonce and arm the 30s pong deadline. Shared
   * by the auto-heartbeat (`startHeartbeat`) and `sendManualPing` so both
   * pings count toward the same `consecutiveFailures` counter — the spec's
   * "3 次无 pong" is a connection-liveness signal, not a path-specific one.
   *
   * Per-ping semantics: each call gets its OWN independent 30s window in
   * `pendingPings` (keyed by nonce). Multiple pings can be in flight at
   * once without their deadlines shadowing each other — only the missing
   * pong for THIS specific nonce counts toward the 30s budget. With the
   * auto-heartbeat sending one ping every 20s and 3 misses tolerated,
   * the worst-case "all 3 unanswered" timeline is roughly 30 + 20 + 30 + 20
   * + 30 ≈ 130s of silence before the connection is declared dead; the
   * typical case (a healthy connection loses pongs but recovers) declares
   * dead within ≈ 90s of the first dropped pong.
   */
  private armPing(nonce: string): void {
    const sentAt = Date.now();
    this.sendRaw({
      v: PROTOCOL_VERSION,
      kind: 'control' as const,
      type: 'ping' as const,
      id: this.makeId(),
      payload: { nonce } satisfies PingPayload,
    });
    const timer = setTimeout(() => {
      // Deadline expired without a matching pong → count one miss.
      this.pendingPings.delete(nonce);
      this.consecutiveFailures += 1;
      if (this._pingHistory.length >= PING_HISTORY_CAP) {
        this._pingHistory = this._pingHistory.slice(1);
      }
      this._pingHistory = [...this._pingHistory, { nonce, sentAt, rttMs: null }];
      this.emitStateChange();

      if (this.consecutiveFailures >= PONG_FAIL_LIMIT) {
        // 3 in a row → dead peer. Force the close; the resulting
        // handleClose path schedules the exponential reconnect.
        this.consecutiveFailures = 0;
        this.socket?.close();
      }
    }, PONG_TIMEOUT_MS);
    this.pendingPings.set(nonce, { sentAt, timer });
  }

  private handlePong(payload: PongPayload): void {
    const pending = this.pendingPings.get(payload.nonce);
    if (!pending) {
      // Stale or unsolicited pong — nothing to ack.
      return;
    }
    clearTimeout(pending.timer);
    this.pendingPings.delete(payload.nonce);
    // Any successful pong resets the failure streak (control.md §3:
    // "连续 3 次" is consecutive, not cumulative).
    this.consecutiveFailures = 0;

    if (this._pingHistory.length >= PING_HISTORY_CAP) {
      this._pingHistory = this._pingHistory.slice(1);
    }
    this._pingHistory = [
      ...this._pingHistory,
      { nonce: payload.nonce, sentAt: pending.sentAt, rttMs: Date.now() - pending.sentAt },
    ];
    this.emitStateChange();
  }

  // ---- Internals: reconnect ------------------------------------------------

  private scheduleReconnect(): void {
    if (!this.shouldReconnect) return;
    this.clearReconnectTimer();
    const exp = Math.min(
      RECONNECT_CAP_MS,
      RECONNECT_BASE_MS * Math.pow(2, this.reconnectAttempt),
    );
    // ±20% jitter, matching the bridge client.
    const jitter = exp * (1 - RECONNECT_JITTER_RATIO + Math.random() * RECONNECT_JITTER_RATIO * 2);
    this.reconnectAttempt += 1;
    this.reconnectTimer = setTimeout(() => {
      this.reconnectTimer = null;
      if (this.shouldReconnect) {
        this.openSocket();
      }
    }, jitter);
  }

  private clearReconnectTimer(): void {
    if (this.reconnectTimer) {
      clearTimeout(this.reconnectTimer);
      this.reconnectTimer = null;
    }
  }

  // ---- Internals: low-level send + state updates --------------------------

  private sendRaw(envelope: EnvelopeType): void {
    const socket = this.socket;
    if (!socket || socket.readyState !== WebSocket.OPEN) {
      // Silent drop — calling send() while offline is a no-op rather than
      // an error, so components like PingTester can be wired before the
      // socket finishes opening without guard code.
      return;
    }
    try {
      socket.send(JSON.stringify(envelope));
    } catch (err) {
      console.warn('[WsClient] send() failed:', err);
    }
  }

  private setConnState(next: ConnState): void {
    if (this._connState === next) return;
    this._connState = next;
    this.emitStateChange();
  }

  private setBridgeStatus(info: BridgeStatusInfo): void {
    this._bridgeStatus = info;
    this.emitStateChange();
  }

  private appendLog(envelope: EnvelopeType): void {
    const next = this._logs.length >= LOG_CAP ? this._logs.slice(1) : this._logs.slice();
    next.push({ receivedAt: Date.now(), envelope });
    this._logs = next;
    this.emitStateChange();
  }

  private emitStateChange(): void {
    for (const listener of this.stateListeners) {
      listener();
    }
  }

  // ---- Internals: id / nonce helpers --------------------------------------

  private makeId(): string {
    return crypto.randomUUID();
  }

  private makeNonce(): string {
    // Full UUID — matches the bridge daemon's nonce generation
    // (packages/bridge/src/client.ts sendPing) and the worker DO's own
    // heartbeat nonce (heartbeat.ts tickHeartbeat). 8-char truncation was
    // nice for human inspection in PingTester but birthday-collides
    // across multiple tabs within the 30s window (2^32 / 2 ≈ 65k draws
    // ≈ 50% collision); keeping the full UUID eliminates the risk for
    // negligible wire-size cost (36 vs 8 chars per nonce).
    return crypto.randomUUID();
  }
}
