// RemotePi web — single WebSocket client (control plane only).
//
// Wires up one persistent connection to the worker domain at
// `${VITE_WSS_URL}/web`, carrying the access token in the URL fragment + the
// second element of the WebSocket subprotocol (per architecture/protocol/
// envelope.md §锁版承诺 and control.md §1).
//
// Responsibilities:
//   - On open: send the control/handshake frame with `{role:'web', token}`.
//   - Send a control/ping every 20s (heartbeat) — generated by us, the
//     counterparty may also ping us; we reply with control/pong carrying
//     the same nonce (control.md §2 / §3).
//   - On pong: clear the matching timer, compute RTT, reset failure counter.
//     Three consecutive timeouts in a row → close + reconnect.
//   - On bridge_status: surface `online` / `changed_at` / `reason` to the UI.
//   - On pi/event: route to the chat-state machine (message_update /
//     message_end / agent_settled / extension_ui_request / queue_update).
//   - On session_state: update sessionPhase + blockedOn (M3 PRD §4.1).
//   - On snapshot: replace the message list (get_messages reply).
//   - On command_result{success:false}: route failure paths.
//       * error.code === 'request_expired' → dialogs (existing `onDialogExpired`).
//       * any failure → InputBar (`onCommandError`) for the non-dialog PRD §4.5 UX.
//   - On invalid envelope: console.warn and discard (web is read-only on
//     the error channel — we never emit `error` frames outbound).
//   - On close / error: state machine drops to `offline`, and unless the
//     caller explicitly disconnected, schedule an exponential reconnect
//     (base 1s, cap 30s, ±20% jitter).
//
// React glue lives in `WsClientContext.tsx`; this file is framework-free so
// the protocol logic stays unit-testable in isolation if/when we add tests.

import {
  Envelope,
  ListDirectoriesResultSchema,
  PROTOCOL_VERSION,
  SessionListResultSchema,
  SessionStatePayloadSchema,
  WorkDirListResultSchema,
  type AbortPayload,
  type BlockedOnEntryPayload,
  type Envelope as EnvelopeType,
  type ExtensionUIResponsePayload,
  type FollowUpPayload,
  type GetMessagesPayload,
  type ListDirectoriesPayload,
  type ListDirectoriesResult,
  type PingPayload,
  type PongPayload,
  type PromptPayload,
  type SessionListEntry,
  type SessionListPayload,
  type SessionListResult,
  type SessionPhase,
  type SessionStatePayload,
  type SteerPayload,
  type WorkDirAddPayload,
  type WorkDirListPayload,
  type WorkDirListResult,
  type WorkDirRemovePayload,
} from '@remotepi/shared';

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/** Tri-state connection machine surfaced by the StatusBar component. */
export type ConnState = 'connecting' | 'online' | 'offline';

/** Latest bridge_status snapshot broadcast by the worker (control.md §4). */
export interface BridgeStatusInfo {
  online: boolean;
  /** ISO-8601 timestamp from the worker (BridgeStatusPayload.changed_at). */
  changedAt: string;
  reason: 'connected' | 'closed' | 'stale';
  /** Local clock at the moment we observed the frame — for UI ordering. */
  receivedAt: number;
}

/** Handler signature for type-scoped subscriptions (`ws.on('pong', …)`). */
export type EnvelopeHandler = (envelope: EnvelopeType) => void;

// ---------------------------------------------------------------------------
// Chat-state types (M3 PRD §4.1 WebState)
// ---------------------------------------------------------------------------

/** A pi message in its native shape. The shared package does not pin
 *  per-message schemas (`SnapshotPayloadSchema.messages` is
 *  `z.array(z.unknown())`) — web treats each entry as opaque JSON. We
 *  expose it as `unknown` so callers narrow with their own helpers if
 *  they need to introspect (e.g. extract a text preview). */
export type AgentMessage = unknown;

/** A streaming draft message — accumulates text_delta events. `text` is
 *  built up locally from consecutive `message_update` payloads carrying
 *  a text delta; `messageId` is the pi-native id (carried in
 *  `data.messageId`) so we can correlate a later `message_end` (which
 *  carries the authoritative full message). The PRD §4.3 wording
 *  requires `message_end` to overwrite / append — using `messageId`
 *  lets us clear the draft when the matching end arrives, even if
 *  another message's deltas interleaved. */
export interface StreamingDraft {
  messageId?: string;
  role?: string;
  text: string;
}

/** Steering / follow_up queue snapshot. Both arrays contain the raw
 *  `content` strings the web submitted (so the UI could surface a
 *  preview). `pi/event` with `event: 'queue_update'` updates this in
 *  place; the bridge forwards the array unchanged from pi's native
 *  shape. */
export interface QueueState {
  steering: string[];
  followUp: string[];
}

/** Broadcast payload for a `command_result{success:false, error.code ===
 *  'request_expired'}`. The chat UI uses this to surface the error to
 *  a dialog (via `reply_to` matching against the dialog's outbound id).
 *  Other failure shapes are intentionally not broadcast — the dialog
 *  auto-closes via the `blocked_on` drop path on the next
 *  `session_state` broadcast (PRD §4.2 关闭规则 + §4.5). */
export interface DialogExpiredNotice {
  /** The web envelope id the dialog used to send its response — web
   *  uses this to find the right dialog. */
  replyTo: string;
  /** The original `request_id` (pi-side UUID) — web also uses this to
   *  locate the dialog even if the outbound envelope id is no longer
   *  in the dialog's memory. */
  requestId: string;
}

/** Subscription callback for dialog-expired notices. Registered alongside
 *  the regular `on()` type listener so dialog components don't need to
 *  re-parse the envelope. */
export type DialogExpiredHandler = (notice: DialogExpiredNotice) => void;

/** Callback fired by the WsClient when an inbound envelope carries a
 *  `reply_to` matching an id a subscriber previously registered for.
 *  Used by the recovery ceremony (`recovery.ts`) to wait for the
 *  dual-query replies without coupling itself to the central
 *  `handleControlFrame` / `handlePiFrame` routing — the central
 *  handlers still update `sessionPhase` / `messages` for everyone
 *  observing the store; this callback is the "I personally want to
 *  know" channel for the gate. Multiple subscribers may register
 *  for the same id (fan-out); the resolver is called with the
 *  matched envelope verbatim. */
export type ReplyResolver = (envelope: EnvelopeType) => void;

/** Broadcast payload for any non-dialog `command_result{success:false}`
 *  (PRD §4.5 — ordinary commands: prompt / steer / follow_up). The
 *  InputBar shows a temporary error banner ("pi 已不再处理该请求，
 *  可能是 idle 超时 kill") and does not retry. The handler is fired
 *  only when the inbound envelope's `reply_to` matches a prompt /
 *  steer / follow_up envelope id the web issued — so a stray failure
 *  for someone else's outbound id is silently dropped. */
export interface CommandErrorNotice {
  /** The web envelope id that the failing command was issued with. */
  replyTo: string;
  /** Bridge-translated error code (string; bridge always sets one). */
  code: string;
  /** Human-readable bridge-side error message. */
  message: string;
}

/** Subscription callback for ordinary-command errors. Same shape as
 *  `DialogExpiredHandler` but distinct so a component that wants only
 *  one of the two notifications doesn't accidentally subscribe to both. */
export type CommandErrorHandler = (notice: CommandErrorNotice) => void;

// ---------------------------------------------------------------------------
// Constants — pulled out for readability and to make the protocol contract
// easy to audit against docs/architecture/protocol/control.md.
// ---------------------------------------------------------------------------

/** Subprotocol slot 0 — version tag, see envelope.md §锁版承诺. */
const SUBPROTOCOL_VERSION = 'remotepi.v1';

/** Heartbeat cadence — control.md §2 (also §配套常量). */
const PING_INTERVAL_MS = 20_000;

/** Per-ping deadline before counting it as a miss — control.md §3. */
const PONG_TIMEOUT_MS = 30_000;

/** Consecutive misses tolerated before we declare the peer dead. */
const PONG_FAIL_LIMIT = 3;

/** Exponential reconnect base, capped at RECONNECT_CAP_MS. */
const RECONNECT_BASE_MS = 1_000;
const RECONNECT_CAP_MS = 30_000;
/** ±20% jitter matches the bridge client (PRD §2 / §6). */
const RECONNECT_JITTER_RATIO = 0.2;

/** Messages + blocked-on array caps — keep memory bounded across long
 *  sessions. The PRD does not specify caps; 1k messages covers a long
 *  coding session and stays well under browser memory pressure. */
const MESSAGES_CAP = 1_000;
/** Queue cap — practical upper bound on outstanding user submissions. */
const QUEUE_CAP = 200;

// ---------------------------------------------------------------------------
// WsClient — plain class, no React dependency
// ---------------------------------------------------------------------------

export class WsClient {
  private readonly url: string;

  private socket: WebSocket | null = null;
  private token: string | null = null;

  // Connection machine state -------------------------------------------------
  private _connState: ConnState = 'offline';
  private _bridgeStatus: BridgeStatusInfo | null = null;

  // Chat-state (M3 PRD §4.1) -------------------------------------------------
  private _messages: AgentMessage[] = [];
  private _streamingDraft: StreamingDraft | null = null;
  /** Set when the current streaming draft has already received a
   *  `*_delta` event (text_delta / thinking_delta / defensive
   *  top-level fallback). Reset when the draft is cleared (snapshot /
   *  message_end / reconnect / recovery) OR a new `message_start`
   *  arrives. While set, a `*_end` event carrying the full content
   *  is DROPPED — the draft already holds the accumulated text from
   *  the deltas, so appending `*_end`'s full-content field would
   *  duplicate the text until the matching `message_end` overwrites
   *  via `upsertMessage` (a noticeable flicker in the UI).
   *
   *  The flag is per-draft, not per-event: a stream that emits
   *  `text_delta*` then `thinking_end` (cross-block) still treats
   *  the `thinking_end` as redundant — the reasoning content from
   *  the matching `thinking_delta*` already accumulated into the
   *  draft, so re-appending would duplicate. The flag resets on
   *  `message_start` (new draft) so a stream that jumps straight to
   *  `*_end` (rare: non-token-chunk providers that don't emit any
   *  `*_delta`) still has the full-text fallback path available. */
  private _draftHasDelta = false;
  private _queue: QueueState = { steering: [], followUp: [] };
  private _sessionPhase: SessionPhase | null = null;
  private _blockedOn: BlockedOnEntryPayload[] = [];

  // M4 choice-page state (tasks/m4/07) ---------------------------------------
  /** Mirror of `bridge/state.json` `work_dirs` array — the user-saved
   *  work directory list. Refreshed on every `work_dir_list` reply
   *  (and after every `work_dir_add` / `work_dir_remove` mutation;
   *  those operations invalidate the snapshot, so the
   *  ChoicePage refreshes by re-issuing `work_dir_list` immediately
   *  after a mutation). The web does not persist this list itself —
   *  bridge is the source of truth. */
  private _workDirs: string[] = [];
  /** Mirror of the URL hash's `work_dir` component (钉子 1 / §4.1).
   *  Maintained by `setCurrentWorkDir()` — App.tsx calls it on every
   *  `hashchange` so the ChoicePage's "create new session" button can
   *  resolve which `work_dir` to send on the next outbound `pi/prompt`
   *  (the ChoicePage uses it for navigation but does not auto-fill
   *  outbound pi commands — task 08 wires that. Today the value
   *  flows into `session_list` outbound automation: web always sets
   *  `payload.work_dir` to this value when querying the session list
   *  per 裁定 A 操作惯例. */
  private _currentWorkDir: string | null = null;
  /** Latest `session_list` reply — the sessions under the current
   *  `work_dir`. ChoicePage level=2 reads this directly. Empty array
   *  before the first query lands; replaced wholesale on every reply
   *  (the bridge sends the full filtered list each time, not a delta).
   *  `null` distinguishes "not yet queried" from "queried and empty"
   *  so the ChoicePage can show a placeholder vs an empty list. */
  private _sessionList: SessionListEntry[] | null = null;
  /** Transient cache for `list_directories` replies — keyed by outbound
   *  envelope id (the bridge echoes `reply_to`, which equals our
   *  outbound id). ChoicePage's DirectoryBrowser uses this to render
   *  the entries list after the user navigates. NOT part of the
   *  useSyncExternalStore state — components consume via the type
   *  listener (`wsClient.on('list_directories', handler)` in M3
   *  fashion) or via the inline `onEntries` callback we expose.
   *  Kept in a Map (rather than a single field) so two concurrent
   *  browser navigations don't shadow each other; entries are
   *  one-shot — the DirectoryBrowser reads them once and we drop the
   *  map entry on consumption. */
  private readonly listDirResults = new Map<string, { entries: Array<{ name: string; path: string }> }>();
  /** Transient `work_dir_list` / `work_dir_add` / `work_dir_remove`
   *  outcome cache — keyed by outbound id. ChoicePage's
   *  DirectoryBrowser "选择" button waits for the
   *  `work_dir_add` result to decide whether to advance. We keep
   *  both success (`ok: true`) and failure (`ok: false` + `error`)
   *  outcomes so error UI can render the bridge-side message. */
  private readonly workDirResults = new Map<
    string,
    { ok: boolean; error?: { code: string; message: string } }
  >();

  // Heartbeat bookkeeping ----------------------------------------------------
  private pingTimer: ReturnType<typeof setInterval> | null = null;
  /** Outstanding outbound nonces and the timeout awaiting their pong. */
  private pendingPings = new Map<
    string,
    { sentAt: number; timer: ReturnType<typeof setTimeout> }
  >();
  private consecutiveFailures = 0;

  // Reconnect bookkeeping ----------------------------------------------------
  private reconnectAttempt = 0;
  private reconnectTimer: ReturnType<typeof setTimeout> | null = null;
  /** Set false by `disconnect()` to suppress the auto-reconnect loop. */
  private shouldReconnect = false;

  // Subscriptions ------------------------------------------------------------
  /** State listeners (used by useSyncExternalStore). */
  private stateListeners = new Set<() => void>();
  /** Type-scoped envelope listeners (`ws.on('pong', handler)`). */
  private typeListeners = new Map<EnvelopeType['type'], Set<EnvelopeHandler>>();
  /** Dialog-expired listeners — only fired on
   *  `command_result{success:false, error.code === 'request_expired'}`. */
  private dialogExpiredListeners = new Set<DialogExpiredHandler>();
  /** Ordinary-command error listeners — fired on any
   *  `command_result{success:false, reply_to ∈ our prompt/steer/follow_up
   *  outbound ids}` (PRD §4.5). */
  private commandErrorListeners = new Set<CommandErrorHandler>();
  /** Outbound envelope ids issued by `sendPrompt` / `sendSteer` /
   *  `sendFollowUp` — kept (small ring) so we can match a later
   *  `command_result{success:false}` by `reply_to` and decide whether
   *  to fire `onCommandError`. The map also lets dialog-expired
   *  matching share the same outbound-id knowledge (dialogs use
   *  `sendExtensionUIResponse`, which uses a different path). */
  private outboundCommandIds = new Set<string>();
  /** Cap on the outbound-id ring so a long-lived session doesn't grow
   *  unbounded (each id is ~36 chars). 200 mirrors QUEUE_CAP — the
   *  queue's practical upper bound on outstanding user submissions. */
  private readonly OUTBOUND_IDS_CAP = QUEUE_CAP;
  /** Reply-to resolvers — the recovery ceremony (`recovery.ts`)
   *  registers callbacks keyed by the outbound id it generated for
   *  its `pi/get_messages` and `control/get_state` queries. When a
   *  matching inbound envelope arrives (matched on `reply_to`),
   *  every registered callback is invoked. The ceremony is the only
   *  current consumer; future subsystems (e.g. an explicit
   *  "refresh history" button) can register additional resolvers
   *  against the same id for fan-out, or against fresh ids for
   *  independent queries. We key by `reply_to` rather than by
   *  `reply_to + type` because outbound ids are UUIDs — collisions
   *  are practically impossible and a fan-out API keeps the surface
   *  simple. The map has no explicit dispose path — cleanup happens
   *  via the unsubscribe closure returned by `registerReplyResolver`,
   *  which the recovery ceremony invokes from `cancelActive()`.
   *  `dispatchReplyResolvers` also drops the entry on
   *  each match (one-shot semantics), so a normal reply-yes-and-done
   *  cycle leaves nothing behind. */
  private replyResolvers = new Map<string, Set<ReplyResolver>>();

  constructor(url: string) {
    this.url = url;
  }

  // ---- Read-only state ------------------------------------------------------

  get connState(): ConnState {
    return this._connState;
  }

  get bridgeStatus(): BridgeStatusInfo | null {
    return this._bridgeStatus;
  }

  get messages(): readonly AgentMessage[] {
    return this._messages;
  }

  get streamingDraft(): StreamingDraft | null {
    return this._streamingDraft;
  }

  get queue(): QueueState {
    return this._queue;
  }

  /** Current pi subprocess phase. `null` until the first
   *  `session_state` frame arrives (or the recovery ceremony's
   *  `get_state` reply). The PhaseIndicator renders a placeholder
   *  while this is null. */
  get sessionPhase(): SessionPhase | null {
    return this._sessionPhase;
  }

  get blockedOn(): readonly BlockedOnEntryPayload[] {
    return this._blockedOn;
  }

  // ---- M4 choice-page state (tasks/m4/07) ----------------------------------

  /** Latest `work_dir_list` snapshot — the user-saved work directories
   *  (mirror of `bridge/state.json`). Empty array until the first
   *  query lands. */
  get workDirs(): readonly string[] {
    return this._workDirs;
  }

  /** Mirror of the hash's `work_dir` component (钉子 1 / PRD §4.1).
   *  `null` when the hash has no `work_dir` (ChoicePage level=1). */
  get currentWorkDir(): string | null {
    return this._currentWorkDir;
  }

  /** Latest `session_list` reply — the sessions under the current
   *  `work_dir`. `null` until the first query lands (so ChoicePage
   *  level=2 can show a "loading" placeholder vs an empty list). */
  get sessionList(): readonly SessionListEntry[] | null {
    return this._sessionList;
  }

  // ---- Subscriptions -------------------------------------------------------

  /**
   * Subscribe to ANY state change. Used by `useSyncExternalStore` —
   * `getSnapshot` is called on every fire; the React layer decides whether
   * the returned slice changed identity and skips re-render if not.
   */
  subscribe = (listener: () => void): (() => void) => {
    this.stateListeners.add(listener);
    return () => {
      this.stateListeners.delete(listener);
    };
  };

  /**
   * Subscribe to a specific envelope type. The handler is called once per
   * inbound frame whose `type` matches. Returns an unsubscribe function.
   */
  on(type: EnvelopeType['type'], handler: EnvelopeHandler): () => void {
    let set = this.typeListeners.get(type);
    if (!set) {
      set = new Set();
      this.typeListeners.set(type, set);
    }
    set.add(handler);
    return () => {
      set?.delete(handler);
    };
  }

  /**
   * Subscribe to dialog-expired notices (command_result with
   * `error.code === 'request_expired'`). Returns an unsubscribe
   * function. Registered separately from `on()` so dialog components
   * don't have to re-parse the envelope shape — they just receive a
   * `{replyTo, requestId}` payload.
   */
  onDialogExpired(handler: DialogExpiredHandler): () => void {
    this.dialogExpiredListeners.add(handler);
    return () => {
      this.dialogExpiredListeners.delete(handler);
    };
  }

  /**
   * Subscribe to ordinary-command error notices (PRD §4.5 — prompt /
   * steer / follow_up that fail with `command_result{success:false}`).
   * Fires only when the inbound envelope's `reply_to` matches a
   * prompt / steer / follow_up envelope id the web issued (so a
   * failure with a foreign `reply_to` is silently dropped). Returns an
   * unsubscribe function.
   */
  onCommandError(handler: CommandErrorHandler): () => void {
    this.commandErrorListeners.add(handler);
    return () => {
      this.commandErrorListeners.delete(handler);
    };
  }

  /**
   * Register a callback to be invoked when an inbound envelope carries
   * `reply_to === replyToId`. Used by the recovery ceremony to await
   * the dual-query replies (`pi/get_messages` → `pi/snapshot`,
   * `control/get_state` → `control/result`). The callback receives the
   * matched envelope verbatim — the ceremony is responsible for any
   * shape narrowing (it's the only consumer right now and knows
   * exactly which type it's waiting for).
   *
   * Multiple subscribers may register against the same id (fan-out);
   * each callback fires independently. Returns an unsubscribe
   * function. Subscriptions are auto-removed when the matching reply
   * is dispatched (one-shot) — the recovery ceremony expects to
   * consume a single reply and then move on, so a leaky subscription
   * that lingers across the next ceremony would surprise a future
   * caller. The auto-removal happens inside `dispatchReplyResolvers`.
   *
   * `replyToId` is the outbound envelope id the caller put in their
   * request's `id` field; the bridge's outstanding-commands table
   * (task 04) echoes that id into the reply's `reply_to` field
   * (`snapshot` for get_messages, `result` for get_state).
   */
  registerReplyResolver(replyToId: string, resolver: ReplyResolver): () => void {
    let set = this.replyResolvers.get(replyToId);
    if (set === undefined) {
      set = new Set();
      this.replyResolvers.set(replyToId, set);
    }
    set.add(resolver);
    return () => {
      const current = this.replyResolvers.get(replyToId);
      if (current === undefined) return;
      current.delete(resolver);
      if (current.size === 0) {
        this.replyResolvers.delete(replyToId);
      }
    };
  }

  // ---- Lifecycle -----------------------------------------------------------

  /**
   * Open a new connection (closing any existing one). `token` must be the
   * non-empty value parsed from `location.hash` — it travels in slot 1 of
   * the WebSocket subprotocol AND in the handshake payload, per envelope.md
   * §锁版承诺.
   */
  connect(token: string): void {
    if (!token) return;
    this.teardownSocket();
    this.token = token;
    this.shouldReconnect = true;
    this.openSocket();
  }

  /** Close and stay closed. Cancels any pending reconnect timer. */
  disconnect(): void {
    this.shouldReconnect = false;
    this.clearReconnectTimer();
    this.teardownSocket();
    if (this._connState !== 'offline') {
      this.setConnState('offline');
    }
  }

  /** Reset chat state — used on disconnect/reconnect and on recovery
   *  retry so a stale snapshot from a previous session doesn't bleed
   *  into the new one. Bridge status is preserved — only the M3
   *  chat fields + the outbound-id ring are wiped. The outbound ring
   *  must be cleared so a late `command_result{success:false}` from
   *  the previous session can't trigger a phantom error banner on
   *  the new session (PRD §4.5: only failures for the current
   *  session should surface). */
  resetChatState(): void {
    this._messages = [];
    this._streamingDraft = null;
    this._draftHasDelta = false;
    this._queue = { steering: [], followUp: [] };
    this._sessionPhase = null;
    this._blockedOn = [];
    this.outboundCommandIds.clear();
    this.emitStateChange();
  }

  // ---- M4 choice-page state setters (tasks/m4/07) --------------------------

  /** Mirror the URL hash's `work_dir` component into the store.
   *  App.tsx calls this on every `hashchange` (in addition to its
   *  normal `setToken` re-derivation) so the ChoicePage's "create
   *  new session" button can read the current directory off the
   *  store instead of re-parsing the hash. `null` when the hash has
   *  no `work_dir`. */
  setCurrentWorkDir(workDir: string | null): void {
    if (this._currentWorkDir === workDir) return;
    this._currentWorkDir = workDir;
    this.emitStateChange();
  }

  // ---- Outbound ------------------------------------------------------------

  /**
   * Send a fully-formed envelope. Caller is responsible for `v` / `kind` /
   * `id` / `payload` shape — this method does not auto-fill. The protocol
   * expects every outbound frame to carry a unique `id`; use `crypto.randomUUID`.
   */
  send(envelope: EnvelopeType): void {
    this.sendRaw(envelope);
  }

  /** Send `pi/prompt` — used by the InputBar. */
  sendPrompt(content: string): string {
    return this.sendPiCommand<PromptPayload>('prompt', { content }, 'prompt');
  }

  /** Send `pi/steer` — mid-run insert. */
  sendSteer(content: string): string {
    return this.sendPiCommand<SteerPayload>('steer', { content }, 'steer');
  }

  /** Send `pi/follow_up` — queued message. */
  sendFollowUp(content: string): string {
    return this.sendPiCommand<FollowUpPayload>('follow_up', { content }, 'follow_up');
  }

  /** Send `pi/abort` — empty payload. No-op when phase === 'exited'
   *  on the bridge side (it still answers command_result{success:true}).
   *  Web UI still sends — bridge handles the no-op. */
  sendAbort(): string {
    return this.sendPiCommand<AbortPayload>('abort', {}, null);
  }

  /** Send `pi/get_messages` — optional `since` cursor. */
  sendGetMessages(since?: string): string {
    return this.sendPiCommand<GetMessagesPayload>(
      'get_messages',
      since !== undefined ? { since } : {},
      null,
    );
  }

  /** Send `pi/extension_ui_response` — dialog acknowledgement. The
   *  `cancelled`/`value` shape mirrors the web wire contract defined
   *  in shared `ExtensionUIResponsePayloadSchema`. Returns the
   *  generated envelope id so the dialog component can match it
   *  against a later `command_result{success:false, error.code ===
   *  'request_expired'}` for the late-submission path. */
  sendExtensionUIResponse(payload: ExtensionUIResponsePayload): string {
    return this.sendPiCommand<ExtensionUIResponsePayload>('extension_ui_response', payload, null);
  }

  // ---- M4 control-family commands (tasks/m4/07) ----------------------------
  //
  // These five commands form the ChoicePage's outbound surface; the
  // bridge handles each in its own `control/<type>` handler. Replies
  // arrive as `control/result` with `reply_to` = outbound id — the
  // central `case 'result':` handler updates `_workDirs`,
  // `_sessionList`, and the transient result maps below.

  /** Send `control/list_directories` — DirectoryBrowser navigation
   *  command. `path` optional (缺省 = bridge 列 $HOME). Reply lands
   *  as a `control/result` carrying `data = { entries: [{ name,
   *  path }, …] }`; the result is cached in `listDirResults` keyed
   *  by the returned id so the DirectoryBrowser can read it after
   *  `await sendListDirectories()`. */
  sendListDirectories(path?: string): string {
    const id = this.makeId();
    const payload: ListDirectoriesPayload = path !== undefined ? { path } : {};
    this.sendRaw({
      v: PROTOCOL_VERSION,
      kind: 'control' as const,
      type: 'list_directories' as const,
      id,
      payload,
    });
    return id;
  }

  /** Send `control/work_dir_list` — query the user's saved work
   *  directory list. Reply populates `_workDirs` and is also cached
   *  by id for callers that want to await a specific query (e.g.
   *  ChoicePage refresh after add/remove). */
  sendWorkDirList(): string {
    const id = this.makeId();
    const payload: WorkDirListPayload = {};
    this.sendRaw({
      v: PROTOCOL_VERSION,
      kind: 'control' as const,
      type: 'work_dir_list' as const,
      id,
      payload,
    });
    return id;
  }

  /** Send `control/work_dir_add` — add a path to the user's saved
   *  list. Returns the outbound id so the DirectoryBrowser can
   *  await the result and decide whether to advance to level=2.
   *  The bridge performs the canonical M3 three-piece check
   *  (exists + is directory + readable); failures land as
   *  `result.ok = false` + `error.code` and surface via
   *  `takeWorkDirResult(id)`. */
  sendWorkDirAdd(path: string): string {
    const id = this.makeId();
    const payload: WorkDirAddPayload = { path };
    this.sendRaw({
      v: PROTOCOL_VERSION,
      kind: 'control' as const,
      type: 'work_dir_add' as const,
      id,
      payload,
    });
    return id;
  }

  /** Send `control/work_dir_remove` — remove a path from the saved
   *  list. Per PRD §钉子 3 the bridge does NOT kill any active
   *  PiProcessManager rooted in this directory; removal only makes
   *  the directory unreachable from ChoicePage level=2. */
  sendWorkDirRemove(path: string): string {
    const id = this.makeId();
    const payload: WorkDirRemovePayload = { path };
    this.sendRaw({
      v: PROTOCOL_VERSION,
      kind: 'control' as const,
      type: 'work_dir_remove' as const,
      id,
      payload,
    });
    return id;
  }

  /** Send `control/session_list` — query the session list for one
   *  work directory (裁定 A 操作惯例 — `payload.work_dir` 必带).
   *  `session: <work_dir>` envelope-field convention is NOT applied
   *  here (task 07 scope per the brief — `ChoicePage 阶段命令为
   *  control 族，session_list 带 payload.work_dir（裁定 A）`);
   *  the per-session envelope field lands in task 08 when the
   *  store buckets per-session. Reply populates `_sessionList`
   *  (replaced wholesale on every reply). Returns the outbound id. */
  sendSessionList(workDir: string): string {
    const id = this.makeId();
    const payload: SessionListPayload = { work_dir: workDir };
    this.sendRaw({
      v: PROTOCOL_VERSION,
      kind: 'control' as const,
      type: 'session_list' as const,
      id,
      payload,
    });
    return id;
  }

  // ---- Internals: socket lifecycle ----------------------------------------

  private openSocket(): void {
    if (!this.token) return;
    this.setConnState('connecting');

    let socket: WebSocket;
    try {
      // Slot 0 = version, slot 1 = token (envelope.md §锁版承诺). The token
      // travels separately from the URL so it isn't logged in proxy/CDN
      // access logs.
      socket = new WebSocket(this.url, [SUBPROTOCOL_VERSION, this.token]);
    } catch (err) {
      console.warn('[WsClient] WebSocket construction failed:', err);
      this.scheduleReconnect();
      return;
    }
    this.socket = socket;

    socket.addEventListener('open', this.handleOpen);
    socket.addEventListener('message', this.handleMessage);
    socket.addEventListener('close', this.handleClose);
    socket.addEventListener('error', this.handleError);
  }

  private teardownSocket(): void {
    this.clearHeartbeat();
    if (this.socket) {
      // removeEventListener is a no-op for listeners that weren't registered,
      // so the cleanup path stays straightforward.
      this.socket.close();
      this.socket = null;
    }
  }

  private handleOpen = (): void => {
    this.reconnectAttempt = 0;
    this.consecutiveFailures = 0;
    if (this.token) {
      const handshake = {
        v: PROTOCOL_VERSION,
        kind: 'control' as const,
        type: 'handshake' as const,
        id: this.makeId(),
        payload: { role: 'web' as const, token: this.token },
      };
      this.sendRaw(handshake);
    }
    this.setConnState('online');
    this.startHeartbeat();
  };

  private handleMessage = (event: MessageEvent): void => {
    // Drop messages from a stale socket — happens when connect() swapped
    // us onto a new token mid-flight: the old socket's close has been
    // requested but its buffered message event may still fire on us.
    if (!this.isCurrentSocket(event.target)) return;
    let raw: unknown;
    try {
      raw = JSON.parse(typeof event.data === 'string' ? event.data : '');
    } catch (err) {
      console.warn('[WsClient] inbound JSON parse failed:', err);
      return;
    }
    const parsed = Envelope.safeParse(raw);
    if (!parsed.success) {
      // Per spec: web only logs invalid frames — we never originate `error`
      // frames, so the worker can't tell us "you sent garbage". Drop quietly.
      console.warn('[WsClient] inbound envelope failed schema, discarding:', parsed.error.message);
      return;
    }
    const envelope = parsed.data;
    this.dispatchTypeListeners(envelope);
    this.handleControlFrame(envelope);
    this.handlePiFrame(envelope);
  };

  private dispatchTypeListeners(envelope: EnvelopeType): void {
    const set = this.typeListeners.get(envelope.type);
    if (!set) return;
    for (const handler of set) {
      try {
        handler(envelope);
      } catch (err) {
        // A buggy handler must not break the message loop for other subs.
        console.warn('[WsClient] type listener threw:', err);
      }
    }
  }

  // ---- Internals: control-family routing ----------------------------------

  private handleControlFrame(envelope: EnvelopeType): void {
    if (envelope.kind !== 'control') return;
    switch (envelope.type) {
      case 'ping': {
        // Server-initiated liveness probe — reply with pong carrying the
        // same nonce (or empty if the probe arrived without one). The worker's
        // own heartbeat (§3 of control.md + DO 主动探活) routes through here.
        const pong = {
          v: PROTOCOL_VERSION,
          kind: 'control' as const,
          type: 'pong' as const,
          id: this.makeId(),
          payload: { nonce: envelope.payload.nonce ?? '' },
        };
        this.sendRaw(pong);
        break;
      }
      case 'pong': {
        this.handlePong(envelope.payload);
        break;
      }
      case 'bridge_status': {
        this.setBridgeStatus({
          online: envelope.payload.online,
          changedAt: envelope.payload.changed_at,
          reason: envelope.payload.reason,
          receivedAt: Date.now(),
        });
        break;
      }
      case 'session_state': {
        // M3 PRD §4.1 / §1.2: session_state is the authoritative source
        // for phase + blocked_on. `blocked_on` absence = empty array
        // (envelope evolution rule (a)). We replace the local arrays
        // wholesale — the dialog auto-close rule (PRD §4.2 关闭规则)
        // is implemented by the dialog components observing this
        // array via useEffect and detecting their id dropping out.
        this.setSessionPhase(envelope.payload.phase);
        this.setBlockedOn(envelope.payload.blocked_on ?? []);
        break;
      }
      case 'handshake':
      case 'session_list':
      case 'get_state':
      case 'error':
        // Server-to-client frames we don't act on centrally: handshakes
        // (worker doesn't send us), session_list / get_state / error
        // are read-only on web (logged via the type listener if anyone
        // cares). `result` is handled below — it's the dual-query
        // recovery ceremony's get_state reply and the central
        // `sessionPhase` + `blockedOn` revalidation lives there.
        break;
      case 'result': {
        // `control/result` is the unified reply for session_list
        // (M2), get_state (M3), and the four M4 work-dir /
        // directory-browsing commands. Each command's reply carries
        // a different `data` shape — we revalidate `data`
        // defensively against each schema and only mutate store
        // state when the shape matches; other callers are silently
        // dropped at the type-narrowing step (the schema check
        // fails). The decode for `get_state` is shared with the
        // recovery ceremony via `tryDecodeGetStateData` so the
        // schema lives in one place.
        //
        // M4 choice-page commands also cache their outcome in
        // `workDirResults` (work_dir_list/add/remove success/failure
        // surface) and `listDirResults` (list_directories entries),
        // so the ChoicePage's DirectoryBrowser can await a specific
        // outbound id without re-routing the whole store. Reply-to
        // resolvers (the recovery ceremony) still fire regardless
        // so the gate can mark itself ready / error based on the
        // actual envelope.
        const replyTo = envelope.reply_to;
        // Dispatch by `data` shape — each schema is a one-shot
        // narrowing that returns the parsed payload on success and
        // `null` on mismatch. The four-way chain covers
        // work_dir_list / list_directories / session_list;
        // `work_dir_add` / `work_dir_remove` reply with no `data`
        // (success) or `result.ok = false` (failure), which the
        // generic fallback below handles.
        const workDirList = tryDecodeWorkDirListResult(envelope);
        const listDir = workDirList === null ? tryDecodeListDirectoriesResult(envelope) : null;
        const sessions =
          workDirList === null && listDir === null
            ? tryDecodeSessionListResult(envelope)
            : null;
        if (workDirList !== null) {
          this.setWorkDirs(workDirList.work_dirs);
          if (replyTo !== undefined && replyTo.length > 0) {
            this.workDirResults.set(replyTo, { ok: true });
          }
        } else if (listDir !== null) {
          if (replyTo !== undefined && replyTo.length > 0) {
            this.listDirResults.set(replyTo, { entries: listDir.entries });
          }
        } else if (sessions !== null) {
          this.setSessionList(sessions.sessions);
        } else if (
          replyTo !== undefined &&
          replyTo.length > 0 &&
          // work_dir_add / work_dir_remove success carries no
          // `data`; we cache the success so the DirectoryBrowser
          // can advance. Failures carry `error.code` + `error.message`
          // and land in the same cache with `ok: false`.
          (envelope.payload.ok === false || envelope.payload.ok === true)
        ) {
          this.workDirResults.set(replyTo, {
            ok: envelope.payload.ok,
            ...(envelope.payload.ok === false && envelope.payload.error !== undefined
              ? {
                  error: {
                    code: envelope.payload.error.code,
                    message: envelope.payload.error.message,
                  },
                }
              : {}),
          });
        }
        // get_state reply — phase + blocked_on mirror (M3 §4.1)
        const state = tryDecodeGetStateData(envelope);
        if (state !== null) {
          this.setSessionPhase(state.phase);
          this.setBlockedOn(state.blocked_on ?? []);
        }
        this.dispatchReplyResolvers(envelope);
        break;
      }
    }
  }

  // ---- Internals: pi-family routing ---------------------------------------

  private handlePiFrame(envelope: EnvelopeType): void {
    if (envelope.kind !== 'pi') return;
    switch (envelope.type) {
      case 'snapshot': {
        // get_messages reply — replace the message list wholesale. Per
        // PRD §4.3, `snapshot.messages` is the authoritative history.
        // Element shape is opaque (shared treats it as unknown[]) so we
        // pass the array verbatim — `setMessages` accepts readonly
        // unknown[] elements and the AgentMessage alias is purely a
        // documentation hint.
        this.setMessages(envelope.payload.messages);
        // A snapshot often arrives at the end of a turn — clear any
        // leftover streaming draft so the UI doesn't show stale text.
        this.setStreamingDraft(null);
        // Fire any registered reply-to resolvers (the recovery
        // ceremony awaits the get_messages reply via this hook).
        // Dispatch happens AFTER the store mutation so a resolver
        // that triggers a React re-render (via the ceremony's
        // subscribe listeners) sees the freshest messages when it
        // eventually flips `ready: true`.
        this.dispatchReplyResolvers(envelope);
        break;
      }
      case 'event': {
        this.handlePiEvent(envelope.payload.event, envelope.payload.data);
        break;
      }
      case 'command_result': {
        // Failure paths (PRD §4.5):
        //   - request_expired → dialog subscribers (late dialog submission;
        //     dialog matches by its outbound id).
        //   - any other failure with reply_to matching a tracked prompt /
        //     steer / follow_up outbound id → `onCommandError` so the
        //     InputBar can show the temporary error banner.
        // A failure with reply_to that matches neither path (e.g. an
        // unrelated response observed by another tab) is silently dropped.
        if (!envelope.payload.success) {
          const err = envelope.payload.error;
          const replyTo = envelope.reply_to ?? '';
          if (err?.code === 'request_expired') {
            // See note in DialogExpiredNotice.requestId — web has no
            // way to recover the original pi request_id from the reply,
            // so dialog subscribers match by replyTo alone.
            this.notifyDialogExpired({ replyTo, requestId: '' });
          } else if (replyTo.length > 0 && this.outboundCommandIds.has(replyTo)) {
            this.outboundCommandIds.delete(replyTo);
            this.notifyCommandError({
              replyTo,
              code: err?.code ?? 'unknown',
              message: err?.message ?? 'command failed',
            });
          }
        }
        break;
      }
      case 'prompt':
      case 'steer':
      case 'follow_up':
      case 'abort':
      case 'get_messages':
      case 'extension_ui_response':
        // Commands are web → bridge; the bridge never echoes them back.
        // Anything matching here is unexpected — drop quietly.
        break;
    }
  }

  /** Dispatch a `pi/event` payload by `event` name. Per PRD §4.3 the
   *  web routes by event name; the data shape is intentionally open
   *  (envelope evolution rule (c)) so we extract defensively and
   *  tolerate missing fields by treating them as no-ops. */
  private handlePiEvent(event: string, data: unknown): void {
    switch (event) {
      case 'message_update': {
        // Streaming delta / end. pi 0.85.1's wire shape (verified
        // against `@earendil-works/pi-coding-agent@0.85.1`'s
        // `dist/modes/json-event.js` `toJsonEvent` +
        // `dist/modes/rpc/rpc-mode.js`) is:
        //   `{ assistantMessageEvent: { type, contentIndex,
        //      delta|content|id|toolName|... } }`
        // where `assistantMessageEvent.type` is one of `start` /
        // `text_start` / `text_delta` / `text_end` /
        // `thinking_start` / `thinking_delta` / `thinking_end` /
        // `toolcall_start` / `toolcall_delta` / `toolcall_end` /
        // `done` / `error`.
        //
        // The bug we fix here: `*_delta` accumulates text into the
        // streaming draft, and `*_end` carries the SAME text as a
        // full-content field. If we treat both the same (append on
        // arrival), the draft duplicates its tail on every `*_end`
        // until the matching `message_end` overwrites via
        // `upsertMessage` — a visible flicker. The fix is the
        // `_draftHasDelta` flag: once we've appended any delta for
        // this draft, `*_end` is dropped on arrival.
        const innerType = innerEventType(data);
        if (innerType === 'text_delta' || innerType === 'thinking_delta') {
          // Streaming delta — typewriter appends this to the draft
          // and arms `_draftHasDelta` via `appendStreamingDraft`.
          const delta = extractDeltaText(data);
          if (delta === null) return;
          this.appendStreamingDraft(data, delta);
          return;
        }
        if (innerType === 'text_end' || innerType === 'thinking_end') {
          // Full content block — only useful when no `*_delta`
          // preceded it. While `_draftHasDelta` is set the draft
          // already holds the accumulated text; appending would
          // duplicate. Drop the event.
          if (this._draftHasDelta) return;
          // No prior delta — use the full content as the bootstrap
          // text so a stream that only emits `*_end` (rare: non-
          // token-chunk providers) still renders.
          const full = extractEndContent(data);
          if (full === null) return;
          this.appendStreamingDraft(data, full);
          return;
        }
        // Unknown / defensive-fallback shapes (no inner
        // `assistantMessageEvent`, or top-level `text_delta` /
        // `delta` / `text` / `content`, or nested content array).
        // Treat as deltas — same behaviour as the original
        // `extractTextDelta` fallback — and arm the flag so any
        // later `*_end` is dropped too. (Note: `extractTextDelta`
        // was split into `extractDeltaText` / `extractEndContent`
        // in the same patch that added the `_draftHasDelta` flag;
        // the comment keeps the historical name for traceability.)
        const delta = extractDeltaText(data);
        if (delta === null) return;
        this.appendStreamingDraft(data, delta);
        break;
      }
      case 'message_end': {
        // Authoritative full message — clear the draft and append (or
        // replace) the message in the list. We DO try to deduplicate by
        // messageId (S2 review): if the bridge re-delivers a message_end
        // for an id we already have, slice-and-replace in place so the
        // UI doesn't see two rows for the same logical message.
        const message = extractMessageEndMessage(data);
        if (message === undefined) return;
        const id = extractMessageId(data);
        this.upsertMessage(message, id);
        if (id !== undefined) {
          this.clearStreamingDraft(id);
        } else {
          this.setStreamingDraft(null);
        }
        break;
      }
      case 'agent_settled': {
        // Per PRD §4.3, the UI shows the input-available hint after
        // agent_settled. The actual gating lives in the InputBar
        // (which reads sessionPhase). The session_state broadcast
        // eventually transitions running → idle on its own; this
        // event is the EARLIER signal that the agent has finished
        // its current turn and the input is safe to enable. We don't
        // mutate any state here — components that care about this
        // event can subscribe via `on('event', …)` and switch on
        // the event name. (The InputBar wires this in ChatView.)
        break;
      }
      case 'queue_update': {
        // PRD §4.3: queue_update carries the current steering +
        // followUp arrays. Shape is `{ steering: string[],
        // followUp: string[] }`. Defensive extraction — unknown
        // shape falls back to clearing the queue.
        const next = extractQueueUpdate(data);
        if (next !== null) {
          this.setQueue(next);
        }
        break;
      }
      case 'extension_ui_request':
        // We rely on session_state.blocked_on (the bridge's source
        // of truth) for the dialog list. The original
        // extension_ui_request forward is informational only — it
        // doesn't drive any state mutation in the web client. Dialog
        // components read blockedOn and ignore the event envelope.
        break;
      case 'message_start':
        // New draft starting. Reset `_draftHasDelta` so the next
        // draft starts fresh — a stream that emits `*_end` without
        // preceding `*_delta` (or with deltas that arrive after
        // `*_end` due to an out-of-order bridge forwarding) still
        // has the full-text fallback path available. The draft
        // itself is left untouched: pi typically emits `message_start`
        // BEFORE the first content block, so any pre-existing draft
        // would belong to a previous turn (already cleared by
        // `message_end`); an absent draft here is the normal case
        // and the first `*_delta` / `*_end` creates it.
        this._draftHasDelta = false;
        break;
      case 'turn_start':
      case 'turn_end':
      case 'agent_start':
      case 'agent_end':
      case 'tool_execution_start':
      case 'tool_execution_update':
      case 'tool_execution_end':
      case 'entry_appended':
      case 'ui_prompt_start':
      case 'ui_prompt_end':
      default:
        // Open set — unknown events are ignored. PRD §4.3 + envelope
        // evolution rule (c): web does not pin event names beyond
        // the rendering-relevant ones above.
        break;
    }
  }

  private handleClose = (event: CloseEvent): void => {
    // Same stale-event guard as handleMessage — when teardownSocket() closed
    // a prior socket (e.g. during token swap), the close event still fires
    // on it AFTER we've moved on. Comparing event.target to `this.socket`
    // detects that case and lets us skip the (now incorrect) reconnect.
    if (!this.isCurrentSocket(event.target)) return;
    this.socket = null;
    this.clearHeartbeat();
    if (this._connState !== 'offline') {
      this.setConnState('offline');
    }
    if (this.shouldReconnect) {
      this.scheduleReconnect();
    }
  };

  private handleError = (event: Event): void => {
    // Mirror the close guard: stale errors from a previous socket must not
    // flip the *current* connection into the offline state. The real close
    // event will follow for the active socket and drives the reconnect.
    //
    // We unconditionally set offline here — the redundant `connState ===
    // 'online'` guard from before this fix was misleading. The browser/Node
    // contract is that every `error` event is followed by a `close` event
    // on the same socket (per the WHATWG HTML spec); handleClose is the
    // authoritative path that clears the socket and schedules the
    // reconnect. handleError exists only to flip the visible status
    // earlier so the UI doesn't sit on a stale 'online' label while the
    // closing handshake is still draining.
    if (!this.isCurrentSocket(event.target)) return;
    this.setConnState('offline');
  };

  /**
   * True iff `target` is the WebSocket we currently consider live. Used to
   * discard late events from a socket that was replaced via connect().
   */
  private isCurrentSocket(target: EventTarget | null): boolean {
    return target !== null && target === this.socket;
  }

  // ---- Internals: heartbeat ------------------------------------------------

  private startHeartbeat(): void {
    this.clearHeartbeat();
    this.pingTimer = setInterval(() => {
      this.armPing(this.makeNonce());
    }, PING_INTERVAL_MS);
  }

  private clearHeartbeat(): void {
    if (this.pingTimer) {
      clearInterval(this.pingTimer);
      this.pingTimer = null;
    }
    for (const pending of this.pendingPings.values()) {
      clearTimeout(pending.timer);
    }
    this.pendingPings.clear();
    this.consecutiveFailures = 0;
  }

  /**
   * Send a ping with the given nonce and arm the 30s pong deadline. The
   * spec's "3 次无 pong" is a connection-liveness signal, so every
   * outbound ping counts toward the same `consecutiveFailures` counter
   * regardless of its source.
   *
   * Per-ping semantics: each call gets its OWN independent 30s window in
   * `pendingPings` (keyed by nonce). Multiple pings can be in flight at
   * once without their deadlines shadowing each other — only the missing
   * pong for THIS specific nonce counts toward the 30s budget. With the
   * auto-heartbeat sending one ping every 20s and 3 misses tolerated,
   * the worst-case "all 3 unanswered" timeline is roughly 30 + 20 + 30 + 20
   * + 30 ≈ 130s of silence before the connection is declared dead; the
   * typical case (a healthy connection loses pongs but recovers) declares
   * dead within ≈ 90s of the first dropped pong.
   */
  private armPing(nonce: string): void {
    const sentAt = Date.now();
    this.sendRaw({
      v: PROTOCOL_VERSION,
      kind: 'control' as const,
      type: 'ping' as const,
      id: this.makeId(),
      payload: { nonce } satisfies PingPayload,
    });
    const timer = setTimeout(() => {
      // Deadline expired without a matching pong → count one miss.
      this.pendingPings.delete(nonce);
      this.consecutiveFailures += 1;
      this.emitStateChange();

      if (this.consecutiveFailures >= PONG_FAIL_LIMIT) {
        // 3 in a row → dead peer. Force the close; the resulting
        // handleClose path schedules the exponential reconnect.
        this.consecutiveFailures = 0;
        this.socket?.close();
      }
    }, PONG_TIMEOUT_MS);
    this.pendingPings.set(nonce, { sentAt, timer });
  }

  private handlePong(payload: PongPayload): void {
    const pending = this.pendingPings.get(payload.nonce);
    if (!pending) {
      // Stale or unsolicited pong — nothing to ack.
      return;
    }
    clearTimeout(pending.timer);
    this.pendingPings.delete(payload.nonce);
    // Any successful pong resets the failure streak (control.md §3:
    // "连续 3 次" is consecutive, not cumulative).
    this.consecutiveFailures = 0;
    this.emitStateChange();
  }

  // ---- Internals: reconnect ------------------------------------------------

  private scheduleReconnect(): void {
    if (!this.shouldReconnect) return;
    this.clearReconnectTimer();
    const exp = Math.min(RECONNECT_CAP_MS, RECONNECT_BASE_MS * Math.pow(2, this.reconnectAttempt));
    // ±20% jitter, matching the bridge client.
    const jitter = exp * (1 - RECONNECT_JITTER_RATIO + Math.random() * RECONNECT_JITTER_RATIO * 2);
    this.reconnectAttempt += 1;
    this.reconnectTimer = setTimeout(() => {
      this.reconnectTimer = null;
      if (this.shouldReconnect) {
        this.openSocket();
      }
    }, jitter);
  }

  private clearReconnectTimer(): void {
    if (this.reconnectTimer) {
      clearTimeout(this.reconnectTimer);
      this.reconnectTimer = null;
    }
  }

  // ---- Internals: low-level send + state updates --------------------------

  /** `trackable` is the set of command types whose outbound ids the
   *  client should remember so a later `command_result{success:false}`
   *  can be matched against them via `reply_to`. PRD §4.5 / W1:
   *  ordinary commands (prompt / steer / follow_up) trigger an
   *  InputBar error banner; abort / get_messages / extension_ui_response
   *  have their own response paths and are NOT tracked. */
  private sendPiCommand<P>(type: 'prompt', payload: P, trackable: 'prompt'): string;
  private sendPiCommand<P>(type: 'steer', payload: P, trackable: 'steer'): string;
  private sendPiCommand<P>(type: 'follow_up', payload: P, trackable: 'follow_up'): string;
  private sendPiCommand<P>(type: 'abort', payload: P, trackable: null): string;
  private sendPiCommand<P>(type: 'get_messages', payload: P, trackable: null): string;
  private sendPiCommand<P>(type: 'extension_ui_response', payload: P, trackable: null): string;
  private sendPiCommand<P>(
    type: string,
    payload: P,
    _trackable: 'prompt' | 'steer' | 'follow_up' | null,
  ): string {
    const id = this.makeId();
    this.sendRaw({
      v: PROTOCOL_VERSION,
      kind: 'pi' as const,
      type: type as 'prompt',
      id,
      payload: payload as { content: string },
    });
    if (_trackable !== null) {
      this.trackOutboundId(id);
    }
    return id;
  }

  private sendRaw(envelope: EnvelopeType): void {
    const socket = this.socket;
    if (!socket || socket.readyState !== WebSocket.OPEN) {
      // Silent drop — calling send() while offline is a no-op rather than
      // an error, so components like the InputBar can be wired before
      // the socket finishes opening without guard code.
      return;
    }
    try {
      socket.send(JSON.stringify(envelope));
    } catch (err) {
      console.warn('[WsClient] send() failed:', err);
    }
  }

  private setConnState(next: ConnState): void {
    if (this._connState === next) return;
    this._connState = next;
    this.emitStateChange();
  }

  /** Fan-out a single inbound envelope to every resolver registered
   *  for its `reply_to` id, then auto-remove the now-consumed
   *  subscription (one-shot). A resolver that throws is logged
   *  with `console.warn` and swallowed — a buggy subscriber
   *  must not break the inbound frame loop for the rest of the
   *  chain, but the throw itself is the kind of operator-visible
   *  signal the web package's console.warn budget DOES cover
   *  (it indicates a programming error in the recovery ceremony
   *  or any future reply-resolver consumer). Returns silently
   *  when the envelope has no `reply_to` (most control / pi
   *  frames don't, and we don't want to scan an empty key). */
  private dispatchReplyResolvers(envelope: EnvelopeType): void {
    const replyTo = envelope.reply_to;
    if (replyTo === undefined || replyTo.length === 0) return;
    const set = this.replyResolvers.get(replyTo);
    if (set === undefined) return;
    // Snapshot the set so a resolver that unsubscribes during dispatch
    // (via its returned cleanup) doesn't shift the iteration; the
    // unsubscribe path also short-circuits the size-zero delete below
    // by checking the live map.
    const resolvers = Array.from(set);
    // Drop the entry BEFORE invoking — a resolver that calls
    // registerReplyResolver with the same id during dispatch would
    // otherwise see its own callback fired in the same tick (loop
    // re-iteration semantics). The ceremony's contract is "one
    // reply per id, no double-fire".
    this.replyResolvers.delete(replyTo);
    for (const resolver of resolvers) {
      try {
        resolver(envelope);
      } catch (err) {
        // Logged-and-swallowed — see the JSDoc on this method.
        // A throw here is a bug in the resolver (the recovery
        // ceremony's outcome recording, or any future fan-out
        // consumer); the inbound frame loop must keep going for
        // the other subscribers in the chain.
        // eslint-disable-next-line no-console
        console.warn('[WsClient] reply resolver threw:', err);
      }
    }
  }

  private setBridgeStatus(info: BridgeStatusInfo): void {
    this._bridgeStatus = info;
    this.emitStateChange();
  }

  private setMessages(messages: readonly unknown[]): void {
    // SnapshotPayloadSchema defines `messages` as `z.array(z.unknown())`
    // — the shared package deliberately does NOT pin per-message shapes.
    // We pass the array through verbatim; the AgentMessage type alias
    // is documentation only (it widens to `unknown`).
    const sliced =
      messages.length > MESSAGES_CAP
        ? messages.slice(messages.length - MESSAGES_CAP)
        : messages.slice();
    this._messages = sliced;
    this.emitStateChange();
  }

  /** Append a fresh message, or — if `messageId` is provided AND we
   *  already have an entry with that id — slice-and-replace in place
   *  (S2 review). The bridge re-delivers a `message_end` for the
   *  same id when pi re-emits a snapshot mid-turn; without the
   *  replace path the message list would double-row. When the id is
   *  missing or doesn't match an existing entry we fall back to a
   *  plain append. */
  private upsertMessage(message: AgentMessage, messageId: string | undefined): void {
    if (messageId !== undefined) {
      const idx = this.findMessageIndexById(messageId);
      if (idx !== -1) {
        const next = this._messages.slice();
        next[idx] = message;
        this._messages = next.length > MESSAGES_CAP ? next.slice(next.length - MESSAGES_CAP) : next;
        this.emitStateChange();
        return;
      }
    }
    const next = [...this._messages, message];
    this._messages = next.length > MESSAGES_CAP ? next.slice(next.length - MESSAGES_CAP) : next;
    this.emitStateChange();
  }

  /** Linear scan — MESSAGES_CAP is 1k so a naive walk is fine and
   *  avoids dragging a parallel id index through every mutation. */
  private findMessageIndexById(messageId: string): number {
    for (let i = 0; i < this._messages.length; i += 1) {
      const candidate = this._messages[i];
      if (candidate !== null && typeof candidate === 'object') {
        const obj = candidate as Record<string, unknown>;
        for (const key of ['messageId', 'message_id', 'id']) {
          if (typeof obj[key] === 'string' && obj[key] === messageId) {
            return i;
          }
        }
      }
    }
    return -1;
  }

  private setStreamingDraft(draft: StreamingDraft | null): void {
    this._streamingDraft = draft;
    // Centralised reset point: whenever the draft goes to null we
    // also drop `_draftHasDelta` so the next draft starts fresh —
    // covers `snapshot` (clear leftover draft) and `message_end`
    // (authoritative replacement). `appendStreamingDraft` re-arms
    // it on the first delta of the next draft.
    if (draft === null) {
      this._draftHasDelta = false;
    }
    this.emitStateChange();
  }

  private appendStreamingDraft(data: unknown, delta: string): void {
    const id = extractMessageId(data);
    const role = extractRole(data);
    const existing = this._streamingDraft;
    // Match the existing draft by id when possible — if the messageId
    // shifts (e.g. pi emits a fresh draft after an error), start a new
    // one rather than concatenating onto a stale buffer.
    if (existing !== null && (id === undefined || existing.messageId === id)) {
      this._streamingDraft = {
        ...(existing.messageId !== undefined
          ? { messageId: existing.messageId }
          : id !== undefined
            ? { messageId: id }
            : {}),
        ...(existing.role !== undefined
          ? { role: existing.role }
          : role !== undefined
            ? { role }
            : {}),
        text: existing.text + delta,
      };
    } else {
      this._streamingDraft = {
        ...(id !== undefined ? { messageId: id } : {}),
        ...(role !== undefined ? { role } : {}),
        text: delta,
      };
    }
    // We just appended a delta — the draft now holds accumulated
    // text. Any subsequent `*_end` for this draft would carry the
    // same text as a full-content field, so flag it to make
    // `handlePiEvent`'s `message_update` branch skip the `*_end`
    // extraction. The flag is reset on draft clear (snapshot /
    // message_end / resetChatState) and on `message_start` (new
    // draft).
    this._draftHasDelta = true;
    this.emitStateChange();
  }

  private clearStreamingDraft(messageId: string): void {
    const draft = this._streamingDraft;
    if (draft !== null && draft.messageId === messageId) {
      // Route through `setStreamingDraft(null)` so the
      // `_draftHasDelta` reset stays centralised — a future refactor
      // that touches one path but not the other would silently
      // re-introduce the `*_end` duplication bug.
      this.setStreamingDraft(null);
    }
  }

  private setQueue(queue: QueueState): void {
    const clamp = (arr: string[]): string[] =>
      arr.length > QUEUE_CAP ? arr.slice(arr.length - QUEUE_CAP) : arr.slice();
    this._queue = { steering: clamp(queue.steering), followUp: clamp(queue.followUp) };
    this.emitStateChange();
  }

  private setSessionPhase(phase: SessionPhase): void {
    if (this._sessionPhase === phase) return;
    this._sessionPhase = phase;
    this.emitStateChange();
  }

  private setBlockedOn(entries: BlockedOnEntryPayload[]): void {
    // Shallow-equality guard: `entries.slice()` would always produce
    // a fresh array reference, forcing every `useBlockedOn` consumer
    // to re-render even when the contents are identical. The PRD
    // §4.2 dialog-close rule fires off a `session_state` broadcast
    // on every state machine transition (not just dialog changes),
    // so a no-op blocked_on update is common — comparing lengths
    // and per-element identity keeps React quiet in that hot path.
    // The entries themselves are the store's authoritative objects,
    // so reference equality is sufficient (no deep walk needed).
    const current = this._blockedOn;
    if (
      current.length === entries.length &&
      current.every((entry, idx) => entry === entries[idx])
    ) {
      return;
    }
    this._blockedOn = entries.slice();
    this.emitStateChange();
  }

  // ---- M4 setters (tasks/m4/07) -------------------------------------------

  /** Replace the in-memory `work_dirs` mirror with a fresh snapshot
   *  from the bridge (reply of `work_dir_list`). Called from the
   *  central `case 'result'` handler; the ChoicePage subscribes
   *  via `useWorkDirs()`. Identity-stable guard: replacing with the
   *  same array (length + element-wise equality) is a no-op so
   *  React skips the re-render. */
  private setWorkDirs(dirs: readonly string[]): void {
    const current = this._workDirs;
    if (
      current.length === dirs.length &&
      current.every((d, idx) => d === dirs[idx])
    ) {
      return;
    }
    this._workDirs = dirs.slice();
    this.emitStateChange();
  }

  /** Replace the in-memory session list mirror with a fresh reply
   *  from the bridge (reply of `session_list`). `null` is reserved
   *  for "not yet queried" (so ChoicePage can render a loading
   *  state); the bridge never sends `null` itself — it sends
   *  `[]` for "no sessions". */
  private setSessionList(entries: readonly SessionListEntry[]): void {
    this._sessionList = entries.slice();
    this.emitStateChange();
  }

  private notifyDialogExpired(notice: DialogExpiredNotice): void {
    for (const listener of this.dialogExpiredListeners) {
      try {
        listener(notice);
      } catch (_err) {
        // Listener exceptions are programming bugs — swallow silently
        // rather than spamming the operator console (PRD constraint:
        // the web package is allowed a fixed budget of console.warn
        // calls; dialog-expired is not in that set). A future debug
        // session can attach a temporary listener with its own log
        // to surface the failure.
      }
    }
  }

  private notifyCommandError(notice: CommandErrorNotice): void {
    for (const listener of this.commandErrorListeners) {
      try {
        listener(notice);
      } catch (_err) {
        // Same rationale as notifyDialogExpired — listener bugs are
        // swallowed silently to honour the web-package console budget.
      }
    }
  }

  /** Remember an outbound id so a future `command_result{success:false}`
   *  with that id as `reply_to` can be routed to `onCommandError`.
   *  Capped at OUTBOUND_IDS_CAP; on overflow we evict in insertion
   *  order (Set preserves insertion order) so the window stays small
   *  and recent ids always survive. */
  private trackOutboundId(id: string): void {
    if (this.outboundCommandIds.size >= this.OUTBOUND_IDS_CAP) {
      const oldest = this.outboundCommandIds.values().next();
      if (!oldest.done) this.outboundCommandIds.delete(oldest.value);
    }
    this.outboundCommandIds.add(id);
  }

  private emitStateChange(): void {
    for (const listener of this.stateListeners) {
      listener();
    }
  }

  // ---- M4 result consumers (tasks/m4/07) -----------------------------------

  /** Consume a cached `list_directories` reply by outbound id.
   *  Returns the entries array or `null` if no reply has arrived
   *  yet. One-shot — the cache entry is removed after the read so a
   *  second `takeListDirResult(id)` returns `null` (mirrors the
   *  WsClient's one-shot reply-resolver pattern). The
   *  DirectoryBrowser awaits the reply with a short-lived
   *  `registerReplyResolver`-style polling loop on this surface;
   *  task 08 will replace the manual await with a typed Promise
   *  (out of scope here — the brief pins task 07 to the ChoicePage
   *  + DirectoryBrowser + hash plumbing; full async command plumbing
   *  is task 08). */
  takeListDirResult(id: string): Array<{ name: string; path: string }> | null {
    const cached = this.listDirResults.get(id);
    if (cached === undefined) return null;
    this.listDirResults.delete(id);
    return cached.entries.slice();
  }

  /** Consume a cached `work_dir_list` / `work_dir_add` /
   *  `work_dir_remove` outcome by outbound id. One-shot semantics
   *  match `takeListDirResult`. Returns `{ ok: true }` on success
   *  (no data shape), `{ ok: false, error: { code, message } }` on
   *  failure. `null` if no reply has arrived yet. */
  takeWorkDirResult(id: string): { ok: boolean; error?: { code: string; message: string } } | null {
    const cached = this.workDirResults.get(id);
    if (cached === undefined) return null;
    this.workDirResults.delete(id);
    return cached;
  }

  private makeId(): string {
    return crypto.randomUUID();
  }

  private makeNonce(): string {
    // Full UUID — matches the bridge daemon's nonce generation
    // (packages/bridge/src/client.ts sendPing) and the worker DO's own
    // heartbeat nonce (heartbeat.ts tickHeartbeat). 8-char truncation
    // birthday-collides across multiple tabs within the 30s window
    // (2^32 / 2 ≈ 65k draws ≈ 50% collision); keeping the full UUID
    // eliminates the risk for negligible wire-size cost (36 vs 8
    // chars per nonce).
    return crypto.randomUUID();
  }
}

// ---------------------------------------------------------------------------
// Helpers — envelope-level shape extraction + dual-ceremony shared decoder
// ---------------------------------------------------------------------------

/** Try to decode a `control/result` reply as a `get_state` payload.
 *  Returns the validated `SessionStatePayload` on success, or `null`
 *  when the envelope isn't a get_state result (e.g. a session_list
 *  reply, an `ok: false` failure, or a success with a malformed
 *  `data` shape). Both the WsClient's central `case 'result'`
 *  handler AND the recovery ceremony (`recovery.ts`) consume this
 *  — the schema check lives in one place so a future schema change
 *  ripples through both call sites automatically. The schema is
 *  intentionally strict (`SessionStatePayloadSchema` is a `z.object`
 *  without `.passthrough`); we revalidate on every inbound reply so
 *  a corrupt bridge (e.g. an empty `blocked_on`) can't poison the
 *  store state. */
export function tryDecodeGetStateData(envelope: EnvelopeType): SessionStatePayload | null {
  if (envelope.kind !== 'control' || envelope.type !== 'result') return null;
  if (envelope.payload.ok !== true) return null;
  if (envelope.payload.data === undefined) return null;
  const validation = SessionStatePayloadSchema.safeParse(envelope.payload.data);
  if (!validation.success) return null;
  return validation.data;
}

// ---------------------------------------------------------------------------
// M4 result-data decoders (tasks/m4/07)
// ---------------------------------------------------------------------------
//
// Each decoder narrows `data` against one of the three result schemas
// (`WorkDirListResult` / `ListDirectoriesResult` / `SessionListResult`)
// introduced in M4 (control.md §6.6 / §6.5 / §7). The central
// `case 'result'` handler in `handleControlFrame` chains them so a
// single inbound reply maps to exactly one cache update. The order
// is arbitrary — each decoder inspects only the envelope's `data`
// field and returns `null` on shape mismatch; the next decoder gets a
// fresh shot. The schemas live in `@remotepi/shared` (`work-dirs.ts` /
// `session-list.ts`) so adding a new result-data shape there ripples
// through automatically.

/** Try to decode a `control/result` reply as a `work_dir_list`
 *  payload (`data: { work_dirs: string[] }`). The WsClient's central
 *  `case 'result'` handler feeds successful decodes into `setWorkDirs`. */
export function tryDecodeWorkDirListResult(
  envelope: EnvelopeType,
): WorkDirListResult | null {
  if (envelope.kind !== 'control' || envelope.type !== 'result') return null;
  if (envelope.payload.ok !== true) return null;
  if (envelope.payload.data === undefined) return null;
  const validation = WorkDirListResultSchema.safeParse(envelope.payload.data);
  if (!validation.success) return null;
  return validation.data;
}

/** Try to decode a `control/result` reply as a `list_directories`
 *  payload (`data: { entries: { name, path }[] }`). Successful
 *  decodes populate the transient `listDirResults` cache keyed by
 *  outbound id (the DirectoryBrowser awaits the reply via
 *  `takeListDirResult(id)`). */
export function tryDecodeListDirectoriesResult(
  envelope: EnvelopeType,
): ListDirectoriesResult | null {
  if (envelope.kind !== 'control' || envelope.type !== 'result') return null;
  if (envelope.payload.ok !== true) return null;
  if (envelope.payload.data === undefined) return null;
  const validation = ListDirectoriesResultSchema.safeParse(envelope.payload.data);
  if (!validation.success) return null;
  return validation.data;
}

/** Try to decode a `control/result` reply as a `session_list`
 *  payload (`data: { sessions: SessionListEntry[] }`). Successful
 *  decodes populate `_sessionList` (ChoicePage level=2 reads this
 *  directly). The schema lives in `@remotepi/shared`/`session-list.ts`. */
export function tryDecodeSessionListResult(
  envelope: EnvelopeType,
): SessionListResult | null {
  if (envelope.kind !== 'control' || envelope.type !== 'result') return null;
  if (envelope.payload.ok !== true) return null;
  if (envelope.payload.data === undefined) return null;
  const validation = SessionListResultSchema.safeParse(envelope.payload.data);
  if (!validation.success) return null;
  return validation.data;
}

/** Coerce a value to a string when it is one. Anything else (number,
 *  boolean, null, undefined, object) returns null so the caller can
 *  fall through to the next candidate field. */
function asStringOrNull(value: unknown): string | null {
  if (typeof value === 'string') return value;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  return null;
}

/** Read the inner `assistantMessageEvent.type` discriminator — used
 *  by `handlePiEvent`'s `message_update` branch to route `*_delta`
 *  vs `*_end` to the right extraction path. Returns `undefined`
 *  when the payload doesn't carry the inner envelope (defensive
 *  fallback shapes) — the caller falls through to the delta path,
 *  which is the original behaviour for any unknown shape. */
function innerEventType(data: unknown): string | undefined {
  if (data === null || typeof data !== 'object') return undefined;
  const inner = (data as Record<string, unknown>).assistantMessageEvent;
  if (inner === null || typeof inner !== 'object') return undefined;
  const t = (inner as Record<string, unknown>).type;
  return typeof t === 'string' ? t : undefined;
}

/** Pluck a streaming delta string from a `*_delta` event payload
 *  (or its top-level equivalent on non-pi builds). The pi 0.85.1
 *  wire shape (verified against
 *  `@earendil-works/pi-coding-agent@0.85.1`'s
 *  `dist/modes/json-event.js` `toJsonEvent` + `dist/modes/rpc/rpc-mode.js`)
 *  is:
 *    { usage, assistantMessageEvent: { type, contentIndex, delta|content|id|toolName|... } }
 *  where the delta field lives under `assistantMessageEvent.delta`
 *  for `text_delta` / `thinking_delta`. The PRD §4.3 wording
 *  pre-dates this transformation — `text_delta` is NOT a top-level
 *  field, it's nested inside `assistantMessageEvent`. The previous
 *  top-level-only lookup produced `null` for every real pi frame,
 *  which is why the typewriter never appeared.
 *
 *  We hit the nested shape first (the real pi wire) and keep the
 *  top-level `text_delta` / `delta` fallback as a defensive net for
 *  unknown / future event variants. `text` / `content` are
 *  intentionally NOT in the fallback list — they're full-text
 *  fields, not incremental updates; including them here would
 *  treat every full payload as a delta and re-trigger the
 *  `*_end` duplication bug for any future shape that also sends
 *  `*_end`. The nested content array fallback is also kept for
 *  the same defensive reason (rare: some non-pi builds).
 *
 *  Returns `null` when nothing usable is found — caller treats
 *  this as a no-op (the matching `message_end` will overwrite
 *  the draft via `upsertMessage`). */
function extractDeltaText(data: unknown): string | null {
  if (data === null || typeof data !== 'object') return null;
  const obj = data as Record<string, unknown>;
  // pi 0.85.1 wire: `data.assistantMessageEvent.delta` for
  // text_delta / thinking_delta.
  const inner = obj.assistantMessageEvent;
  if (inner !== null && typeof inner === 'object') {
    const innerObj = inner as Record<string, unknown>;
    if (
      (innerObj.type === 'text_delta' || innerObj.type === 'thinking_delta') &&
      typeof innerObj.delta === 'string'
    ) {
      // Streaming delta — the typewriter appends this to the draft.
      // We treat thinking_delta like text_delta for now (the user
      // sees the model's reasoning alongside its final answer); a
      // future collapsible thinking panel can branch here without
      // touching the WsClient pipeline.
      return innerObj.delta;
    }
  }
  // Defensive fallback — unknown pi builds (older / future) may
  // put the delta at the top level. Accept `text_delta` / `delta`
  // (the documented incremental-update field names) so a
  // non-standard event still renders instead of silently dropping.
  for (const key of ['text_delta', 'delta']) {
    const value = obj[key];
    if (typeof value === 'string') return value;
  }
  // Nested content array — some non-pi shapes send
  // `{ content: [{type:'text', text:'…'}] }`. Concatenate the text
  // pieces; the caller appends the join so the draft keeps its tail.
  if (Array.isArray(obj.content)) {
    let combined = '';
    for (const piece of obj.content) {
      if (piece !== null && typeof piece === 'object') {
        const text = (piece as Record<string, unknown>).text;
        if (typeof text === 'string') combined += text;
      }
    }
    if (combined.length > 0) return combined;
  }
  return null;
}

/** Pluck the FULL content string from a `*_end` event payload.
 *  Symmetric counterpart to `extractDeltaText`: where
 *  `extractDeltaText` reads `assistantMessageEvent.delta` for
 *  `*_delta`, this reads `assistantMessageEvent.content` for
 *  `*_end`. The `*_end` field is intentionally NOT in the
 *  top-level fallback list — it carries the full block text,
 *  not a delta, so conflating the two would re-trigger the
 *  duplication bug for any future shape that also sends
 *  `*_end`.
 *
 *  Returns `null` for non-end events and shapes without usable
 *  text. The caller decides whether to use the result as a
 *  fallback (when no `*_delta` preceded) or drop it (when the
 *  draft already carries the accumulated text — see
 *  `_draftHasDelta` in `handlePiEvent`). */
function extractEndContent(data: unknown): string | null {
  if (data === null || typeof data !== 'object') return null;
  const obj = data as Record<string, unknown>;
  const inner = obj.assistantMessageEvent;
  if (inner !== null && typeof inner === 'object') {
    const innerObj = inner as Record<string, unknown>;
    if (
      (innerObj.type === 'text_end' || innerObj.type === 'thinking_end') &&
      typeof innerObj.content === 'string'
    ) {
      // `*_end` carries the FULL text of the content block. By
      // the time `end` arrives every preceding `*_delta` has
      // already accumulated the same string in the draft buffer,
      // so the normal case drops this field via `_draftHasDelta`;
      // a stream that emits `end` only (rare: non-token-chunk
      // providers) still renders, and the normal case is
      // idempotent because the matching message_end overwrites
      // via upsertMessage anyway.
      return innerObj.content;
    }
  }
  return null;
}

/** Pluck the `messageId` (or `id`) from an event payload — used to
 *  match streaming drafts against the authoritative message_end. */
function extractMessageId(data: unknown): string | undefined {
  if (data === null || typeof data !== 'object') return undefined;
  const obj = data as Record<string, unknown>;
  for (const key of ['messageId', 'message_id', 'id']) {
    const value = obj[key];
    if (typeof value === 'string') return value;
  }
  return undefined;
}

/** Pluck the `role` from an event payload when present. Three
 *  shapes to handle:
 *
 *  - `data.role` — legacy / direct role on the envelope (rare,
 *    kept as a fallback).
 *  - `data.message.role` — `message_end` / `message_start` shapes:
 *    the role lives on the wrapped message object (UserMessage /
 *    AssistantMessage / ToolResultMessage per pi 0.85.1's
 *    `@earendil-works/pi-ai/dist/types.d.ts`). The previous
 *    top-level-only lookup returned `undefined` for every real
 *    pi `message_end`, leaving the rendered role stuck at
 *    `'unknown'` for assistant turns.
 *  - `data.assistantMessageEvent` present (no `message`) —
 *    `message_update` shape: pi's `toJsonEvent` only allows
 *    assistant role for `message_update` (json-event.js throws
 *    "message_update message is not an assistant message"
 *    otherwise), AND the outer `message` field is dropped during
 *    the transformation. The structural hint that this is an
 *    assistant stream is the presence of `assistantMessageEvent`
 *    itself; infer `'assistant'` so the draft renders the right
 *    role label without a real role lookup.
 *
 *  Returns `undefined` when nothing matches — caller falls back
 *  to the draft's existing role (or `'assistant'` via
 *  `MessageList`'s `draft.role ?? 'assistant'`). */
function extractRole(data: unknown): string | undefined {
  if (data === null || typeof data !== 'object') return undefined;
  const obj = data as Record<string, unknown>;
  if (typeof obj.role === 'string') return obj.role;
  if (obj.message !== null && typeof obj.message === 'object') {
    const inner = (obj.message as Record<string, unknown>).role;
    if (typeof inner === 'string') return inner;
  }
  if (obj.assistantMessageEvent !== undefined) return 'assistant';
  return undefined;
}

/** Pluck the authoritative message from a `message_end` payload.
 *  Returns `undefined` when the shape doesn't carry one — caller
 *  treats this as a no-op (the streaming draft keeps whatever it
 *  has). The return type is `unknown | undefined` rather than the
 *  AgentMessage alias to satisfy `no-redundant-type-constituents`;
 *  AgentMessage IS `unknown` per the doc-comment above, so the
 *  alias would just be noise in the signature. */
function extractMessageEndMessage(data: unknown): unknown {
  if (data === null || typeof data !== 'object') return undefined;
  const obj = data as Record<string, unknown>;
  if ('message' in obj && obj.message !== undefined) {
    return obj.message;
  }
  // Some pi builds put the message fields at the top level — fall
  // back to the whole payload as the message.
  if ('role' in obj || 'content' in obj) {
    return data;
  }
  return undefined;
}

/** Pluck a queue_update payload. Shape is
 *  `{ steering: string[], followUp: string[] }` per PRD §4.3. */
function extractQueueUpdate(data: unknown): QueueState | null {
  if (data === null || typeof data !== 'object') return null;
  const obj = data as Record<string, unknown>;
  const steering = Array.isArray(obj.steering)
    ? obj.steering.filter(asStringOrNull).filter((s): s is string => s !== null)
    : [];
  const followUpRaw = obj.followUp ?? obj.follow_up;
  const followUp = Array.isArray(followUpRaw)
    ? followUpRaw.filter(asStringOrNull).filter((s): s is string => s !== null)
    : [];
  return { steering, followUp };
}
